/*
  emojiData — offline emoji table for the command palette's Emoji chip.

  SOURCE / LICENCE
  ----------------
  Generated from the Unicode Character Database (UCD) as shipped inside
  Python's stdlib `unicodedata` module (Unicode 16.0.0). The character
  names below are UCD data, distributed under the **Unicode License v3**
  (https://www.unicode.org/license.txt) — a permissive BSD-style licence
  that allows commercial redistribution with the copyright notice. It is
  compatible with shipping in a paid product.

  The extra search keywords (`k`) are hand-authored for this repo and are
  covered by this repo's own licence — they are NOT CLDR annotations
  (CLDR is also Unicode-licensed, but we never fetched it: this file was
  produced entirely offline from data already on the build machine).

  NOTHING here is fetched at build time or at runtime. This file IS the
  dataset — that is the point.

  Regenerate: see the generator noted in the commit that added this file.
  Hand-edits are fine; it is plain source.
*/

/** One emoji row. Short keys keep the bundled table small. */
export interface EmojiEntry {
    /** The emoji itself, ready to put on the clipboard (incl. U+FE0F where needed). */
    c: string;
    /** Unicode character name, lowercased. Primary search text. */
    n: string;
    /** Optional extra search keywords, space-separated. */
    k?: string;
}

export const EMOJI: EmojiEntry[] = [
    { c: '🌀', n: 'cyclone' },
    { c: '🌁', n: 'foggy' },
    { c: '🌂', n: 'closed umbrella' },
    { c: '🌃', n: 'night with stars' },
    { c: '🌄', n: 'sunrise over mountains' },
    { c: '🌅', n: 'sunrise' },
    { c: '🌆', n: 'cityscape at dusk' },
    { c: '🌇', n: 'sunset over buildings' },
    { c: '🌈', n: 'rainbow', k: 'rainbow colors peace' },
    { c: '🌉', n: 'bridge at night' },
    { c: '🌊', n: 'water wave' },
    { c: '🌋', n: 'volcano' },
    { c: '🌌', n: 'milky way' },
    { c: '🌍', n: 'earth globe europe-africa', k: 'world earth globe planet' },
    { c: '🌎', n: 'earth globe americas' },
    { c: '🌏', n: 'earth globe asia-australia' },
    { c: '🌐', n: 'globe with meridians' },
    { c: '🌑', n: 'new moon symbol' },
    { c: '🌒', n: 'waxing crescent moon symbol' },
    { c: '🌓', n: 'first quarter moon symbol' },
    { c: '🌔', n: 'waxing gibbous moon symbol' },
    { c: '🌕', n: 'full moon symbol' },
    { c: '🌖', n: 'waning gibbous moon symbol' },
    { c: '🌗', n: 'last quarter moon symbol' },
    { c: '🌘', n: 'waning crescent moon symbol' },
    { c: '🌙', n: 'crescent moon' },
    { c: '🌚', n: 'new moon with face' },
    { c: '🌛', n: 'first quarter moon with face' },
    { c: '🌜', n: 'last quarter moon with face' },
    { c: '🌝', n: 'full moon with face' },
    { c: '🌞', n: 'sun with face' },
    { c: '🌟', n: 'glowing star', k: 'star sparkle' },
    { c: '🌠', n: 'shooting star' },
    { c: '🌡', n: 'thermometer' },
    { c: '🌢', n: 'black droplet' },
    { c: '🌣', n: 'white sun' },
    { c: '🌤', n: 'white sun with small cloud' },
    { c: '🌥', n: 'white sun behind cloud' },
    { c: '🌦', n: 'white sun behind cloud with rain' },
    { c: '🌧', n: 'cloud with rain' },
    { c: '🌨', n: 'cloud with snow' },
    { c: '🌩', n: 'cloud with lightning' },
    { c: '🌪', n: 'cloud with tornado' },
    { c: '🌫', n: 'fog' },
    { c: '🌬', n: 'wind blowing face' },
    { c: '🌭', n: 'hot dog' },
    { c: '🌮', n: 'taco' },
    { c: '🌯', n: 'burrito' },
    { c: '🌰', n: 'chestnut' },
    { c: '🌱', n: 'seedling' },
    { c: '🌲', n: 'evergreen tree' },
    { c: '🌳', n: 'deciduous tree' },
    { c: '🌴', n: 'palm tree' },
    { c: '🌵', n: 'cactus' },
    { c: '🌶', n: 'hot pepper' },
    { c: '🌷', n: 'tulip' },
    { c: '🌸', n: 'cherry blossom' },
    { c: '🌹', n: 'rose' },
    { c: '🌺', n: 'hibiscus' },
    { c: '🌻', n: 'sunflower' },
    { c: '🌼', n: 'blossom' },
    { c: '🌽', n: 'ear of maize' },
    { c: '🌾', n: 'ear of rice' },
    { c: '🌿', n: 'herb' },
    { c: '🍀', n: 'four leaf clover' },
    { c: '🍁', n: 'maple leaf' },
    { c: '🍂', n: 'fallen leaf' },
    { c: '🍃', n: 'leaf fluttering in wind' },
    { c: '🍄', n: 'mushroom' },
    { c: '🍅', n: 'tomato' },
    { c: '🍆', n: 'aubergine' },
    { c: '🍇', n: 'grapes' },
    { c: '🍈', n: 'melon' },
    { c: '🍉', n: 'watermelon' },
    { c: '🍊', n: 'tangerine' },
    { c: '🍋', n: 'lemon' },
    { c: '🍌', n: 'banana' },
    { c: '🍍', n: 'pineapple' },
    { c: '🍎', n: 'red apple' },
    { c: '🍏', n: 'green apple' },
    { c: '🍐', n: 'pear' },
    { c: '🍑', n: 'peach' },
    { c: '🍒', n: 'cherries' },
    { c: '🍓', n: 'strawberry' },
    { c: '🍔', n: 'hamburger' },
    { c: '🍕', n: 'slice of pizza', k: 'pizza food' },
    { c: '🍖', n: 'meat on bone' },
    { c: '🍗', n: 'poultry leg' },
    { c: '🍘', n: 'rice cracker' },
    { c: '🍙', n: 'rice ball' },
    { c: '🍚', n: 'cooked rice' },
    { c: '🍛', n: 'curry and rice' },
    { c: '🍜', n: 'steaming bowl' },
    { c: '🍝', n: 'spaghetti' },
    { c: '🍞', n: 'bread' },
    { c: '🍟', n: 'french fries' },
    { c: '🍠', n: 'roasted sweet potato' },
    { c: '🍡', n: 'dango' },
    { c: '🍢', n: 'oden' },
    { c: '🍣', n: 'sushi' },
    { c: '🍤', n: 'fried shrimp' },
    { c: '🍥', n: 'fish cake with swirl design' },
    { c: '🍦', n: 'soft ice cream' },
    { c: '🍧', n: 'shaved ice' },
    { c: '🍨', n: 'ice cream' },
    { c: '🍩', n: 'doughnut' },
    { c: '🍪', n: 'cookie' },
    { c: '🍫', n: 'chocolate bar' },
    { c: '🍬', n: 'candy' },
    { c: '🍭', n: 'lollipop' },
    { c: '🍮', n: 'custard' },
    { c: '🍯', n: 'honey pot' },
    { c: '🍰', n: 'shortcake' },
    { c: '🍱', n: 'bento box' },
    { c: '🍲', n: 'pot of food' },
    { c: '🍳', n: 'cooking' },
    { c: '🍴', n: 'fork and knife' },
    { c: '🍵', n: 'teacup without handle' },
    { c: '🍶', n: 'sake bottle and cup' },
    { c: '🍷', n: 'wine glass' },
    { c: '🍸', n: 'cocktail glass' },
    { c: '🍹', n: 'tropical drink' },
    { c: '🍺', n: 'beer mug', k: 'beer drink pint' },
    { c: '🍻', n: 'clinking beer mugs' },
    { c: '🍼', n: 'baby bottle' },
    { c: '🍽', n: 'fork and knife with plate' },
    { c: '🍾', n: 'bottle with popping cork' },
    { c: '🍿', n: 'popcorn' },
    { c: '🎀', n: 'ribbon' },
    { c: '🎁', n: 'wrapped present' },
    { c: '🎂', n: 'birthday cake', k: 'cake birthday' },
    { c: '🎃', n: 'jack-o-lantern' },
    { c: '🎄', n: 'christmas tree' },
    { c: '🎅', n: 'father christmas' },
    { c: '🎆', n: 'fireworks' },
    { c: '🎇', n: 'firework sparkler' },
    { c: '🎈', n: 'balloon' },
    { c: '🎉', n: 'party popper', k: 'party celebrate congrats tada' },
    { c: '🎊', n: 'confetti ball', k: 'party celebrate confetti' },
    { c: '🎋', n: 'tanabata tree' },
    { c: '🎌', n: 'crossed flags' },
    { c: '🎍', n: 'pine decoration' },
    { c: '🎎', n: 'japanese dolls' },
    { c: '🎏', n: 'carp streamer' },
    { c: '🎐', n: 'wind chime' },
    { c: '🎑', n: 'moon viewing ceremony' },
    { c: '🎒', n: 'school satchel' },
    { c: '🎓', n: 'graduation cap', k: 'graduate school student' },
    { c: '🎔', n: 'heart with tip on the left' },
    { c: '🎕', n: 'bouquet of flowers' },
    { c: '🎖', n: 'military medal' },
    { c: '🎗', n: 'reminder ribbon' },
    { c: '🎘', n: 'musical keyboard with jacks' },
    { c: '🎙', n: 'studio microphone' },
    { c: '🎚', n: 'level slider' },
    { c: '🎛', n: 'control knobs' },
    { c: '🎜', n: 'beamed ascending musical notes' },
    { c: '🎝', n: 'beamed descending musical notes' },
    { c: '🎞', n: 'film frames' },
    { c: '🎟', n: 'admission tickets' },
    { c: '🎠', n: 'carousel horse' },
    { c: '🎡', n: 'ferris wheel' },
    { c: '🎢', n: 'roller coaster' },
    { c: '🎣', n: 'fishing pole and fish' },
    { c: '🎤', n: 'microphone' },
    { c: '🎥', n: 'movie camera' },
    { c: '🎦', n: 'cinema' },
    { c: '🎧', n: 'headphone' },
    { c: '🎨', n: 'artist palette', k: 'art paint palette design' },
    { c: '🎩', n: 'top hat' },
    { c: '🎪', n: 'circus tent' },
    { c: '🎫', n: 'ticket' },
    { c: '🎬', n: 'clapper board' },
    { c: '🎭', n: 'performing arts' },
    { c: '🎮', n: 'video game' },
    { c: '🎯', n: 'direct hit', k: 'target bullseye goal darts' },
    { c: '🎰', n: 'slot machine' },
    { c: '🎱', n: 'billiards' },
    { c: '🎲', n: 'game die' },
    { c: '🎳', n: 'bowling' },
    { c: '🎴', n: 'flower playing cards' },
    { c: '🎵', n: 'musical note', k: 'music note song' },
    { c: '🎶', n: 'multiple musical notes' },
    { c: '🎷', n: 'saxophone' },
    { c: '🎸', n: 'guitar' },
    { c: '🎹', n: 'musical keyboard' },
    { c: '🎺', n: 'trumpet' },
    { c: '🎻', n: 'violin' },
    { c: '🎼', n: 'musical score' },
    { c: '🎽', n: 'running shirt with sash' },
    { c: '🎾', n: 'tennis racquet and ball' },
    { c: '🎿', n: 'ski and ski boot' },
    { c: '🏀', n: 'basketball and hoop' },
    { c: '🏁', n: 'chequered flag' },
    { c: '🏂', n: 'snowboarder' },
    { c: '🏃', n: 'runner' },
    { c: '🏄', n: 'surfer' },
    { c: '🏅', n: 'sports medal' },
    { c: '🏆', n: 'trophy', k: 'trophy win award first' },
    { c: '🏇', n: 'horse racing' },
    { c: '🏈', n: 'american football' },
    { c: '🏉', n: 'rugby football' },
    { c: '🏊', n: 'swimmer' },
    { c: '🏋', n: 'weight lifter' },
    { c: '🏌', n: 'golfer' },
    { c: '🏍', n: 'racing motorcycle' },
    { c: '🏎', n: 'racing car' },
    { c: '🏏', n: 'cricket bat and ball' },
    { c: '🏐', n: 'volleyball' },
    { c: '🏑', n: 'field hockey stick and ball' },
    { c: '🏒', n: 'ice hockey stick and puck' },
    { c: '🏓', n: 'table tennis paddle and ball' },
    { c: '🏔', n: 'snow capped mountain' },
    { c: '🏕', n: 'camping' },
    { c: '🏖', n: 'beach with umbrella' },
    { c: '🏗', n: 'building construction' },
    { c: '🏘', n: 'house buildings' },
    { c: '🏙', n: 'cityscape' },
    { c: '🏚', n: 'derelict house building' },
    { c: '🏛', n: 'classical building' },
    { c: '🏜', n: 'desert' },
    { c: '🏝', n: 'desert island' },
    { c: '🏞', n: 'national park' },
    { c: '🏟', n: 'stadium' },
    { c: '🏠', n: 'house building', k: 'home house' },
    { c: '🏡', n: 'house with garden' },
    { c: '🏢', n: 'office building' },
    { c: '🏣', n: 'japanese post office' },
    { c: '🏤', n: 'european post office' },
    { c: '🏥', n: 'hospital' },
    { c: '🏦', n: 'bank' },
    { c: '🏧', n: 'automated teller machine' },
    { c: '🏨', n: 'hotel' },
    { c: '🏩', n: 'love hotel' },
    { c: '🏪', n: 'convenience store' },
    { c: '🏫', n: 'school' },
    { c: '🏬', n: 'department store' },
    { c: '🏭', n: 'factory' },
    { c: '🏮', n: 'izakaya lantern' },
    { c: '🏯', n: 'japanese castle' },
    { c: '🏰', n: 'european castle' },
    { c: '🏱', n: 'white pennant' },
    { c: '🏲', n: 'black pennant' },
    { c: '🏳', n: 'waving white flag' },
    { c: '🏴', n: 'waving black flag' },
    { c: '🏵', n: 'rosette' },
    { c: '🏶', n: 'black rosette' },
    { c: '🏷', n: 'label' },
    { c: '🏸', n: 'badminton racquet and shuttlecock' },
    { c: '🏹', n: 'bow and arrow' },
    { c: '🏺', n: 'amphora' },
    { c: '🐀', n: 'rat' },
    { c: '🐁', n: 'mouse' },
    { c: '🐂', n: 'ox' },
    { c: '🐃', n: 'water buffalo' },
    { c: '🐄', n: 'cow' },
    { c: '🐅', n: 'tiger' },
    { c: '🐆', n: 'leopard' },
    { c: '🐇', n: 'rabbit' },
    { c: '🐈', n: 'cat', k: 'cat kitten' },
    { c: '🐉', n: 'dragon' },
    { c: '🐊', n: 'crocodile' },
    { c: '🐋', n: 'whale' },
    { c: '🐌', n: 'snail' },
    { c: '🐍', n: 'snake' },
    { c: '🐎', n: 'horse' },
    { c: '🐏', n: 'ram' },
    { c: '🐐', n: 'goat', k: 'goat' },
    { c: '🐑', n: 'sheep' },
    { c: '🐒', n: 'monkey' },
    { c: '🐓', n: 'rooster' },
    { c: '🐔', n: 'chicken' },
    { c: '🐕', n: 'dog', k: 'dog puppy' },
    { c: '🐖', n: 'pig' },
    { c: '🐗', n: 'boar' },
    { c: '🐘', n: 'elephant' },
    { c: '🐙', n: 'octopus' },
    { c: '🐚', n: 'spiral shell' },
    { c: '🐛', n: 'bug', k: 'bug insect defect' },
    { c: '🐜', n: 'ant' },
    { c: '🐝', n: 'honeybee' },
    { c: '🐞', n: 'lady beetle' },
    { c: '🐟', n: 'fish' },
    { c: '🐠', n: 'tropical fish' },
    { c: '🐡', n: 'blowfish' },
    { c: '🐢', n: 'turtle' },
    { c: '🐣', n: 'hatching chick' },
    { c: '🐤', n: 'baby chick' },
    { c: '🐥', n: 'front-facing baby chick' },
    { c: '🐦', n: 'bird' },
    { c: '🐧', n: 'penguin' },
    { c: '🐨', n: 'koala' },
    { c: '🐩', n: 'poodle' },
    { c: '🐪', n: 'dromedary camel' },
    { c: '🐫', n: 'bactrian camel' },
    { c: '🐬', n: 'dolphin' },
    { c: '🐭', n: 'mouse face' },
    { c: '🐮', n: 'cow face' },
    { c: '🐯', n: 'tiger face' },
    { c: '🐰', n: 'rabbit face' },
    { c: '🐱', n: 'cat face' },
    { c: '🐲', n: 'dragon face' },
    { c: '🐳', n: 'spouting whale' },
    { c: '🐴', n: 'horse face' },
    { c: '🐵', n: 'monkey face' },
    { c: '🐶', n: 'dog face' },
    { c: '🐷', n: 'pig face' },
    { c: '🐸', n: 'frog face' },
    { c: '🐹', n: 'hamster face' },
    { c: '🐺', n: 'wolf face' },
    { c: '🐻', n: 'bear face' },
    { c: '🐼', n: 'panda face' },
    { c: '🐽', n: 'pig nose' },
    { c: '🐾', n: 'paw prints' },
    { c: '🐿', n: 'chipmunk' },
    { c: '👀', n: 'eyes', k: 'eyes look watching' },
    { c: '👁', n: 'eye' },
    { c: '👂', n: 'ear' },
    { c: '👃', n: 'nose' },
    { c: '👄', n: 'mouth' },
    { c: '👅', n: 'tongue' },
    { c: '👆', n: 'white up pointing backhand index' },
    { c: '👇', n: 'white down pointing backhand index' },
    { c: '👈', n: 'white left pointing backhand index' },
    { c: '👉', n: 'white right pointing backhand index' },
    { c: '👊', n: 'fisted hand sign' },
    { c: '👋', n: 'waving hand sign', k: 'wave hi hello bye' },
    { c: '👌', n: 'ok hand sign', k: 'ok perfect' },
    { c: '👍', n: 'thumbs up sign', k: 'thumbsup yes ok approve like +1' },
    { c: '👎', n: 'thumbs down sign', k: 'thumbsdown no disapprove dislike -1' },
    { c: '👏', n: 'clapping hands sign', k: 'clap applause bravo' },
    { c: '👐', n: 'open hands sign' },
    { c: '👑', n: 'crown' },
    { c: '👒', n: 'womans hat' },
    { c: '👓', n: 'eyeglasses' },
    { c: '👔', n: 'necktie' },
    { c: '👕', n: 't-shirt' },
    { c: '👖', n: 'jeans' },
    { c: '👗', n: 'dress' },
    { c: '👘', n: 'kimono' },
    { c: '👙', n: 'bikini' },
    { c: '👚', n: 'womans clothes' },
    { c: '👛', n: 'purse' },
    { c: '👜', n: 'handbag' },
    { c: '👝', n: 'pouch' },
    { c: '👞', n: 'mans shoe' },
    { c: '👟', n: 'athletic shoe' },
    { c: '👠', n: 'high-heeled shoe' },
    { c: '👡', n: 'womans sandal' },
    { c: '👢', n: 'womans boots' },
    { c: '👣', n: 'footprints' },
    { c: '👤', n: 'bust in silhouette' },
    { c: '👥', n: 'busts in silhouette' },
    { c: '👦', n: 'boy' },
    { c: '👧', n: 'girl' },
    { c: '👨', n: 'man' },
    { c: '👩', n: 'woman' },
    { c: '👪', n: 'family' },
    { c: '👫', n: 'man and woman holding hands' },
    { c: '👬', n: 'two men holding hands' },
    { c: '👭', n: 'two women holding hands' },
    { c: '👮', n: 'police officer' },
    { c: '👯', n: 'woman with bunny ears' },
    { c: '👰', n: 'bride with veil' },
    { c: '👱', n: 'person with blond hair' },
    { c: '👲', n: 'man with gua pi mao' },
    { c: '👳', n: 'man with turban' },
    { c: '👴', n: 'older man' },
    { c: '👵', n: 'older woman' },
    { c: '👶', n: 'baby' },
    { c: '👷', n: 'construction worker' },
    { c: '👸', n: 'princess' },
    { c: '👹', n: 'japanese ogre' },
    { c: '👺', n: 'japanese goblin' },
    { c: '👻', n: 'ghost', k: 'ghost boo spooky' },
    { c: '👼', n: 'baby angel' },
    { c: '👽', n: 'extraterrestrial alien' },
    { c: '👾', n: 'alien monster' },
    { c: '👿', n: 'imp' },
    { c: '💀', n: 'skull', k: 'skull dead death' },
    { c: '💁', n: 'information desk person' },
    { c: '💂', n: 'guardsman' },
    { c: '💃', n: 'dancer' },
    { c: '💄', n: 'lipstick' },
    { c: '💅', n: 'nail polish' },
    { c: '💆', n: 'face massage' },
    { c: '💇', n: 'haircut' },
    { c: '💈', n: 'barber pole' },
    { c: '💉', n: 'syringe' },
    { c: '💊', n: 'pill' },
    { c: '💋', n: 'kiss mark' },
    { c: '💌', n: 'love letter' },
    { c: '💍', n: 'ring' },
    { c: '💎', n: 'gem stone' },
    { c: '💏', n: 'kiss' },
    { c: '💐', n: 'bouquet' },
    { c: '💑', n: 'couple with heart' },
    { c: '💒', n: 'wedding' },
    { c: '💓', n: 'beating heart' },
    { c: '💔', n: 'broken heart', k: 'heartbreak sad breakup' },
    { c: '💕', n: 'two hearts' },
    { c: '💖', n: 'sparkling heart' },
    { c: '💗', n: 'growing heart' },
    { c: '💘', n: 'heart with arrow' },
    { c: '💙', n: 'blue heart' },
    { c: '💚', n: 'green heart' },
    { c: '💛', n: 'yellow heart' },
    { c: '💜', n: 'purple heart' },
    { c: '💝', n: 'heart with ribbon' },
    { c: '💞', n: 'revolving hearts' },
    { c: '💟', n: 'heart decoration' },
    { c: '💠', n: 'diamond shape with a dot inside' },
    { c: '💡', n: 'electric light bulb', k: 'idea lightbulb' },
    { c: '💢', n: 'anger symbol' },
    { c: '💣', n: 'bomb' },
    { c: '💤', n: 'sleeping symbol', k: 'sleep zzz snore' },
    { c: '💥', n: 'collision symbol' },
    { c: '💦', n: 'splashing sweat symbol' },
    { c: '💧', n: 'droplet' },
    { c: '💨', n: 'dash symbol' },
    { c: '💩', n: 'pile of poo', k: 'poop shit turd' },
    { c: '💪', n: 'flexed biceps', k: 'muscle strong gym flex' },
    { c: '💫', n: 'dizzy symbol' },
    { c: '💬', n: 'speech balloon' },
    { c: '💭', n: 'thought balloon' },
    { c: '💮', n: 'white flower' },
    { c: '💯', n: 'hundred points symbol', k: 'hundred perfect score' },
    { c: '💰', n: 'money bag', k: 'money cash bag rich' },
    { c: '💱', n: 'currency exchange' },
    { c: '💲', n: 'heavy dollar sign' },
    { c: '💳', n: 'credit card' },
    { c: '💴', n: 'banknote with yen sign' },
    { c: '💵', n: 'banknote with dollar sign' },
    { c: '💶', n: 'banknote with euro sign' },
    { c: '💷', n: 'banknote with pound sign' },
    { c: '💸', n: 'money with wings' },
    { c: '💹', n: 'chart with upwards trend and yen sign' },
    { c: '💺', n: 'seat' },
    { c: '💻', n: 'personal computer', k: 'laptop computer code dev' },
    { c: '💼', n: 'briefcase' },
    { c: '💽', n: 'minidisc' },
    { c: '💾', n: 'floppy disk' },
    { c: '💿', n: 'optical disc' },
    { c: '📀', n: 'dvd' },
    { c: '📁', n: 'file folder', k: 'folder directory' },
    { c: '📂', n: 'open file folder' },
    { c: '📃', n: 'page with curl' },
    { c: '📄', n: 'page facing up' },
    { c: '📅', n: 'calendar', k: 'calendar date' },
    { c: '📆', n: 'tear-off calendar' },
    { c: '📇', n: 'card index' },
    { c: '📈', n: 'chart with upwards trend', k: 'chart graph growth up' },
    { c: '📉', n: 'chart with downwards trend', k: 'chart graph down loss' },
    { c: '📊', n: 'bar chart' },
    { c: '📋', n: 'clipboard' },
    { c: '📌', n: 'pushpin', k: 'pin pinned' },
    { c: '📍', n: 'round pushpin' },
    { c: '📎', n: 'paperclip' },
    { c: '📏', n: 'straight ruler' },
    { c: '📐', n: 'triangular ruler' },
    { c: '📑', n: 'bookmark tabs' },
    { c: '📒', n: 'ledger' },
    { c: '📓', n: 'notebook' },
    { c: '📔', n: 'notebook with decorative cover' },
    { c: '📕', n: 'closed book' },
    { c: '📖', n: 'open book' },
    { c: '📗', n: 'green book' },
    { c: '📘', n: 'blue book' },
    { c: '📙', n: 'orange book' },
    { c: '📚', n: 'books' },
    { c: '📛', n: 'name badge' },
    { c: '📜', n: 'scroll' },
    { c: '📝', n: 'memo', k: 'note write memo' },
    { c: '📞', n: 'telephone receiver' },
    { c: '📟', n: 'pager' },
    { c: '📠', n: 'fax machine' },
    { c: '📡', n: 'satellite antenna' },
    { c: '📢', n: 'public address loudspeaker' },
    { c: '📣', n: 'cheering megaphone' },
    { c: '📤', n: 'outbox tray' },
    { c: '📥', n: 'inbox tray' },
    { c: '📦', n: 'package' },
    { c: '📧', n: 'e-mail symbol', k: 'email mail' },
    { c: '📨', n: 'incoming envelope' },
    { c: '📩', n: 'envelope with downwards arrow above' },
    { c: '📪', n: 'closed mailbox with lowered flag' },
    { c: '📫', n: 'closed mailbox with raised flag' },
    { c: '📬', n: 'open mailbox with raised flag' },
    { c: '📭', n: 'open mailbox with lowered flag' },
    { c: '📮', n: 'postbox' },
    { c: '📯', n: 'postal horn' },
    { c: '📰', n: 'newspaper' },
    { c: '📱', n: 'mobile phone', k: 'phone mobile smartphone' },
    { c: '📲', n: 'mobile phone with rightwards arrow at left' },
    { c: '📳', n: 'vibration mode' },
    { c: '📴', n: 'mobile phone off' },
    { c: '📵', n: 'no mobile phones' },
    { c: '📶', n: 'antenna with bars' },
    { c: '📷', n: 'camera', k: 'camera photo picture' },
    { c: '📸', n: 'camera with flash' },
    { c: '📹', n: 'video camera' },
    { c: '📺', n: 'television' },
    { c: '📻', n: 'radio' },
    { c: '📼', n: 'videocassette' },
    { c: '📽', n: 'film projector' },
    { c: '📾', n: 'portable stereo' },
    { c: '📿', n: 'prayer beads' },
    { c: '🔀', n: 'twisted rightwards arrows' },
    { c: '🔁', n: 'clockwise rightwards and leftwards open circle arrows' },
    { c: '🔂', n: 'clockwise rightwards and leftwards open circle arrows with circled one overlay' },
    { c: '🔃', n: 'clockwise downwards and upwards open circle arrows' },
    { c: '🔄', n: 'anticlockwise downwards and upwards open circle arrows' },
    { c: '🔅', n: 'low brightness symbol' },
    { c: '🔆', n: 'high brightness symbol' },
    { c: '🔇', n: 'speaker with cancellation stroke' },
    { c: '🔈', n: 'speaker' },
    { c: '🔉', n: 'speaker with one sound wave' },
    { c: '🔊', n: 'speaker with three sound waves' },
    { c: '🔋', n: 'battery' },
    { c: '🔌', n: 'electric plug' },
    { c: '🔍', n: 'left-pointing magnifying glass', k: 'search find magnify zoom' },
    { c: '🔎', n: 'right-pointing magnifying glass' },
    { c: '🔏', n: 'lock with ink pen' },
    { c: '🔐', n: 'closed lock with key' },
    { c: '🔑', n: 'key', k: 'key password' },
    { c: '🔒', n: 'lock', k: 'lock secure private' },
    { c: '🔓', n: 'open lock', k: 'unlock open' },
    { c: '🔔', n: 'bell' },
    { c: '🔕', n: 'bell with cancellation stroke' },
    { c: '🔖', n: 'bookmark' },
    { c: '🔗', n: 'link symbol', k: 'link url chain' },
    { c: '🔘', n: 'radio button' },
    { c: '🔙', n: 'back with leftwards arrow above' },
    { c: '🔚', n: 'end with leftwards arrow above' },
    { c: '🔛', n: 'on with exclamation mark with left right arrow above' },
    { c: '🔜', n: 'soon with rightwards arrow above' },
    { c: '🔝', n: 'top with upwards arrow above' },
    { c: '🔞', n: 'no one under eighteen symbol' },
    { c: '🔟', n: 'keycap ten' },
    { c: '🔠', n: 'input symbol for latin capital letters' },
    { c: '🔡', n: 'input symbol for latin small letters' },
    { c: '🔢', n: 'input symbol for numbers' },
    { c: '🔣', n: 'input symbol for symbols' },
    { c: '🔤', n: 'input symbol for latin letters' },
    { c: '🔥', n: 'fire', k: 'fire lit hot flame' },
    { c: '🔦', n: 'electric torch' },
    { c: '🔧', n: 'wrench' },
    { c: '🔨', n: 'hammer' },
    { c: '🔩', n: 'nut and bolt' },
    { c: '🔪', n: 'hocho' },
    { c: '🔫', n: 'pistol' },
    { c: '🔬', n: 'microscope' },
    { c: '🔭', n: 'telescope' },
    { c: '🔮', n: 'crystal ball' },
    { c: '🔯', n: 'six pointed star with middle dot' },
    { c: '🔰', n: 'japanese symbol for beginner' },
    { c: '🔱', n: 'trident emblem' },
    { c: '🔲', n: 'black square button' },
    { c: '🔳', n: 'white square button' },
    { c: '🔴', n: 'large red circle' },
    { c: '🔵', n: 'large blue circle' },
    { c: '🔶', n: 'large orange diamond' },
    { c: '🔷', n: 'large blue diamond' },
    { c: '🔸', n: 'small orange diamond' },
    { c: '🔹', n: 'small blue diamond' },
    { c: '🔺', n: 'up-pointing red triangle' },
    { c: '🔻', n: 'down-pointing red triangle' },
    { c: '🔼', n: 'up-pointing small red triangle' },
    { c: '🔽', n: 'down-pointing small red triangle' },
    { c: '🔾', n: 'lower right shadowed white circle' },
    { c: '🔿', n: 'upper right shadowed white circle' },
    { c: '🕀', n: 'circled cross pommee' },
    { c: '🕁', n: 'cross pommee with half-circle below' },
    { c: '🕂', n: 'cross pommee' },
    { c: '🕃', n: 'notched left semicircle with three dots' },
    { c: '🕄', n: 'notched right semicircle with three dots' },
    { c: '🕅', n: 'symbol for marks chapter' },
    { c: '🕆', n: 'white latin cross' },
    { c: '🕇', n: 'heavy latin cross' },
    { c: '🕈', n: 'celtic cross' },
    { c: '🕉', n: 'om symbol' },
    { c: '🕊', n: 'dove of peace' },
    { c: '🕋', n: 'kaaba' },
    { c: '🕌', n: 'mosque' },
    { c: '🕍', n: 'synagogue' },
    { c: '🕎', n: 'menorah with nine branches' },
    { c: '🕏', n: 'bowl of hygieia' },
    { c: '🕐', n: 'clock face one oclock' },
    { c: '🕑', n: 'clock face two oclock' },
    { c: '🕒', n: 'clock face three oclock' },
    { c: '🕓', n: 'clock face four oclock' },
    { c: '🕔', n: 'clock face five oclock' },
    { c: '🕕', n: 'clock face six oclock' },
    { c: '🕖', n: 'clock face seven oclock' },
    { c: '🕗', n: 'clock face eight oclock' },
    { c: '🕘', n: 'clock face nine oclock' },
    { c: '🕙', n: 'clock face ten oclock' },
    { c: '🕚', n: 'clock face eleven oclock' },
    { c: '🕛', n: 'clock face twelve oclock' },
    { c: '🕜', n: 'clock face one-thirty' },
    { c: '🕝', n: 'clock face two-thirty' },
    { c: '🕞', n: 'clock face three-thirty' },
    { c: '🕟', n: 'clock face four-thirty' },
    { c: '🕠', n: 'clock face five-thirty' },
    { c: '🕡', n: 'clock face six-thirty' },
    { c: '🕢', n: 'clock face seven-thirty' },
    { c: '🕣', n: 'clock face eight-thirty' },
    { c: '🕤', n: 'clock face nine-thirty' },
    { c: '🕥', n: 'clock face ten-thirty' },
    { c: '🕦', n: 'clock face eleven-thirty' },
    { c: '🕧', n: 'clock face twelve-thirty' },
    { c: '🕨', n: 'right speaker' },
    { c: '🕩', n: 'right speaker with one sound wave' },
    { c: '🕪', n: 'right speaker with three sound waves' },
    { c: '🕫', n: 'bullhorn' },
    { c: '🕬', n: 'bullhorn with sound waves' },
    { c: '🕭', n: 'ringing bell' },
    { c: '🕮', n: 'book' },
    { c: '🕯', n: 'candle' },
    { c: '🕰', n: 'mantelpiece clock' },
    { c: '🕱', n: 'black skull and crossbones' },
    { c: '🕲', n: 'no piracy' },
    { c: '🕳', n: 'hole' },
    { c: '🕴', n: 'man in business suit levitating' },
    { c: '🕵', n: 'sleuth or spy' },
    { c: '🕶', n: 'dark sunglasses' },
    { c: '🕷', n: 'spider' },
    { c: '🕸', n: 'spider web' },
    { c: '🕹', n: 'joystick' },
    { c: '🕺', n: 'man dancing' },
    { c: '🕻', n: 'left hand telephone receiver' },
    { c: '🕼', n: 'telephone receiver with page' },
    { c: '🕽', n: 'right hand telephone receiver' },
    { c: '🕾', n: 'white touchtone telephone' },
    { c: '🕿', n: 'black touchtone telephone' },
    { c: '🖀', n: 'telephone on top of modem' },
    { c: '🖁', n: 'clamshell mobile phone' },
    { c: '🖂', n: 'back of envelope' },
    { c: '🖃', n: 'stamped envelope' },
    { c: '🖄', n: 'envelope with lightning' },
    { c: '🖅', n: 'flying envelope' },
    { c: '🖆', n: 'pen over stamped envelope' },
    { c: '🖇', n: 'linked paperclips' },
    { c: '🖈', n: 'black pushpin' },
    { c: '🖉', n: 'lower left pencil' },
    { c: '🖊', n: 'lower left ballpoint pen' },
    { c: '🖋', n: 'lower left fountain pen' },
    { c: '🖌', n: 'lower left paintbrush' },
    { c: '🖍', n: 'lower left crayon' },
    { c: '🖎', n: 'left writing hand' },
    { c: '🖏', n: 'turned ok hand sign' },
    { c: '🖐', n: 'raised hand with fingers splayed' },
    { c: '🖑', n: 'reversed raised hand with fingers splayed' },
    { c: '🖒', n: 'reversed thumbs up sign' },
    { c: '🖓', n: 'reversed thumbs down sign' },
    { c: '🖔', n: 'reversed victory hand' },
    { c: '🖕', n: 'reversed hand with middle finger extended' },
    { c: '🖖', n: 'raised hand with part between middle and ring fingers' },
    { c: '🖗', n: 'white down pointing left hand index' },
    { c: '🖘', n: 'sideways white left pointing index' },
    { c: '🖙', n: 'sideways white right pointing index' },
    { c: '🖚', n: 'sideways black left pointing index' },
    { c: '🖛', n: 'sideways black right pointing index' },
    { c: '🖜', n: 'black left pointing backhand index' },
    { c: '🖝', n: 'black right pointing backhand index' },
    { c: '🖞', n: 'sideways white up pointing index' },
    { c: '🖟', n: 'sideways white down pointing index' },
    { c: '🖠', n: 'sideways black up pointing index' },
    { c: '🖡', n: 'sideways black down pointing index' },
    { c: '🖢', n: 'black up pointing backhand index' },
    { c: '🖣', n: 'black down pointing backhand index' },
    { c: '🖤', n: 'black heart' },
    { c: '🖥', n: 'desktop computer' },
    { c: '🖦', n: 'keyboard and mouse' },
    { c: '🖧', n: 'three networked computers' },
    { c: '🖨', n: 'printer' },
    { c: '🖩', n: 'pocket calculator' },
    { c: '🖪', n: 'black hard shell floppy disk' },
    { c: '🖫', n: 'white hard shell floppy disk' },
    { c: '🖬', n: 'soft shell floppy disk' },
    { c: '🖭', n: 'tape cartridge' },
    { c: '🖮', n: 'wired keyboard' },
    { c: '🖯', n: 'one button mouse' },
    { c: '🖰', n: 'two button mouse' },
    { c: '🖱', n: 'three button mouse' },
    { c: '🖲', n: 'trackball' },
    { c: '🖳', n: 'old personal computer' },
    { c: '🖴', n: 'hard disk' },
    { c: '🖵', n: 'screen' },
    { c: '🖶', n: 'printer icon' },
    { c: '🖷', n: 'fax icon' },
    { c: '🖸', n: 'optical disc icon' },
    { c: '🖹', n: 'document with text' },
    { c: '🖺', n: 'document with text and picture' },
    { c: '🖻', n: 'document with picture' },
    { c: '🖼', n: 'frame with picture' },
    { c: '🖽', n: 'frame with tiles' },
    { c: '🖾', n: 'frame with an x' },
    { c: '🖿', n: 'black folder' },
    { c: '🗀', n: 'folder' },
    { c: '🗁', n: 'open folder' },
    { c: '🗂', n: 'card index dividers' },
    { c: '🗃', n: 'card file box' },
    { c: '🗄', n: 'file cabinet' },
    { c: '🗅', n: 'empty note' },
    { c: '🗆', n: 'empty note page' },
    { c: '🗇', n: 'empty note pad' },
    { c: '🗈', n: 'note' },
    { c: '🗉', n: 'note page' },
    { c: '🗊', n: 'note pad' },
    { c: '🗋', n: 'empty document' },
    { c: '🗌', n: 'empty page' },
    { c: '🗍', n: 'empty pages' },
    { c: '🗎', n: 'document' },
    { c: '🗏', n: 'page' },
    { c: '🗐', n: 'pages' },
    { c: '🗑', n: 'wastebasket', k: 'trash delete bin remove' },
    { c: '🗒', n: 'spiral note pad' },
    { c: '🗓', n: 'spiral calendar pad' },
    { c: '🗔', n: 'desktop window' },
    { c: '🗕', n: 'minimize' },
    { c: '🗖', n: 'maximize' },
    { c: '🗗', n: 'overlap' },
    { c: '🗘', n: 'clockwise right and left semicircle arrows' },
    { c: '🗙', n: 'cancellation x' },
    { c: '🗚', n: 'increase font size symbol' },
    { c: '🗛', n: 'decrease font size symbol' },
    { c: '🗜', n: 'compression' },
    { c: '🗝', n: 'old key' },
    { c: '🗞', n: 'rolled-up newspaper' },
    { c: '🗟', n: 'page with circled text' },
    { c: '🗠', n: 'stock chart' },
    { c: '🗡', n: 'dagger knife' },
    { c: '🗢', n: 'lips' },
    { c: '🗣', n: 'speaking head in silhouette' },
    { c: '🗤', n: 'three rays above' },
    { c: '🗥', n: 'three rays below' },
    { c: '🗦', n: 'three rays left' },
    { c: '🗧', n: 'three rays right' },
    { c: '🗨', n: 'left speech bubble' },
    { c: '🗩', n: 'right speech bubble' },
    { c: '🗪', n: 'two speech bubbles' },
    { c: '🗫', n: 'three speech bubbles' },
    { c: '🗬', n: 'left thought bubble' },
    { c: '🗭', n: 'right thought bubble' },
    { c: '🗮', n: 'left anger bubble' },
    { c: '🗯', n: 'right anger bubble' },
    { c: '🗰', n: 'mood bubble' },
    { c: '🗱', n: 'lightning mood bubble' },
    { c: '🗲', n: 'lightning mood' },
    { c: '🗳', n: 'ballot box with ballot' },
    { c: '🗴', n: 'ballot script x' },
    { c: '🗵', n: 'ballot box with script x' },
    { c: '🗶', n: 'ballot bold script x' },
    { c: '🗷', n: 'ballot box with bold script x' },
    { c: '🗸', n: 'light check mark' },
    { c: '🗹', n: 'ballot box with bold check' },
    { c: '🗺', n: 'world map' },
    { c: '🗻', n: 'mount fuji' },
    { c: '🗼', n: 'tokyo tower' },
    { c: '🗽', n: 'statue of liberty' },
    { c: '🗾', n: 'silhouette of japan' },
    { c: '🗿', n: 'moyai' },
    { c: '😀', n: 'grinning face', k: 'smile happy' },
    { c: '😁', n: 'grinning face with smiling eyes' },
    { c: '😂', n: 'face with tears of joy', k: 'lol laughing funny haha' },
    { c: '😃', n: 'smiling face with open mouth', k: 'smile happy' },
    { c: '😄', n: 'smiling face with open mouth and smiling eyes', k: 'smile happy' },
    { c: '😅', n: 'smiling face with open mouth and cold sweat' },
    { c: '😆', n: 'smiling face with open mouth and tightly-closed eyes' },
    { c: '😇', n: 'smiling face with halo' },
    { c: '😈', n: 'smiling face with horns' },
    { c: '😉', n: 'winking face' },
    { c: '😊', n: 'smiling face with smiling eyes', k: 'smile happy blush' },
    { c: '😋', n: 'face savouring delicious food' },
    { c: '😌', n: 'relieved face' },
    { c: '😍', n: 'smiling face with heart-shaped eyes', k: 'love crush' },
    { c: '😎', n: 'smiling face with sunglasses', k: 'cool sunglasses' },
    { c: '😏', n: 'smirking face' },
    { c: '😐', n: 'neutral face' },
    { c: '😑', n: 'expressionless face' },
    { c: '😒', n: 'unamused face' },
    { c: '😓', n: 'face with cold sweat' },
    { c: '😔', n: 'pensive face' },
    { c: '😕', n: 'confused face', k: 'confused unsure' },
    { c: '😖', n: 'confounded face' },
    { c: '😗', n: 'kissing face' },
    { c: '😘', n: 'face throwing a kiss', k: 'kiss love' },
    { c: '😙', n: 'kissing face with smiling eyes' },
    { c: '😚', n: 'kissing face with closed eyes' },
    { c: '😛', n: 'face with stuck-out tongue' },
    { c: '😜', n: 'face with stuck-out tongue and winking eye' },
    { c: '😝', n: 'face with stuck-out tongue and tightly-closed eyes' },
    { c: '😞', n: 'disappointed face' },
    { c: '😟', n: 'worried face' },
    { c: '😠', n: 'angry face' },
    { c: '😡', n: 'pouting face', k: 'angry mad rage' },
    { c: '😢', n: 'crying face', k: 'cry sad tear' },
    { c: '😣', n: 'persevering face' },
    { c: '😤', n: 'face with look of triumph' },
    { c: '😥', n: 'disappointed but relieved face' },
    { c: '😦', n: 'frowning face with open mouth' },
    { c: '😧', n: 'anguished face' },
    { c: '😨', n: 'fearful face' },
    { c: '😩', n: 'weary face' },
    { c: '😪', n: 'sleepy face' },
    { c: '😫', n: 'tired face' },
    { c: '😬', n: 'grimacing face' },
    { c: '😭', n: 'loudly crying face', k: 'cry sad sobbing' },
    { c: '😮', n: 'face with open mouth' },
    { c: '😯', n: 'hushed face' },
    { c: '😰', n: 'face with open mouth and cold sweat' },
    { c: '😱', n: 'face screaming in fear' },
    { c: '😲', n: 'astonished face' },
    { c: '😳', n: 'flushed face' },
    { c: '😴', n: 'sleeping face', k: 'sleep tired zzz' },
    { c: '😵', n: 'dizzy face' },
    { c: '😶', n: 'face without mouth' },
    { c: '😷', n: 'face with medical mask' },
    { c: '😸', n: 'grinning cat face with smiling eyes' },
    { c: '😹', n: 'cat face with tears of joy' },
    { c: '😺', n: 'smiling cat face with open mouth' },
    { c: '😻', n: 'smiling cat face with heart-shaped eyes' },
    { c: '😼', n: 'cat face with wry smile' },
    { c: '😽', n: 'kissing cat face with closed eyes' },
    { c: '😾', n: 'pouting cat face' },
    { c: '😿', n: 'crying cat face' },
    { c: '🙀', n: 'weary cat face' },
    { c: '🙁', n: 'slightly frowning face' },
    { c: '🙂', n: 'slightly smiling face', k: 'smile slight' },
    { c: '🙃', n: 'upside-down face' },
    { c: '🙄', n: 'face with rolling eyes', k: 'eyeroll annoyed' },
    { c: '🙅', n: 'face with no good gesture' },
    { c: '🙆', n: 'face with ok gesture' },
    { c: '🙇', n: 'person bowing deeply' },
    { c: '🙈', n: 'see-no-evil monkey' },
    { c: '🙉', n: 'hear-no-evil monkey' },
    { c: '🙊', n: 'speak-no-evil monkey' },
    { c: '🙋', n: 'happy person raising one hand' },
    { c: '🙌', n: 'person raising both hands in celebration' },
    { c: '🙍', n: 'person frowning' },
    { c: '🙎', n: 'person with pouting face' },
    { c: '🙏', n: 'person with folded hands', k: 'pray thanks please namaste highfive' },
    { c: '🚀', n: 'rocket', k: 'rocket launch ship fast' },
    { c: '🚁', n: 'helicopter' },
    { c: '🚂', n: 'steam locomotive' },
    { c: '🚃', n: 'railway car' },
    { c: '🚄', n: 'high-speed train' },
    { c: '🚅', n: 'high-speed train with bullet nose' },
    { c: '🚆', n: 'train' },
    { c: '🚇', n: 'metro' },
    { c: '🚈', n: 'light rail' },
    { c: '🚉', n: 'station' },
    { c: '🚊', n: 'tram' },
    { c: '🚋', n: 'tram car' },
    { c: '🚌', n: 'bus' },
    { c: '🚍', n: 'oncoming bus' },
    { c: '🚎', n: 'trolleybus' },
    { c: '🚏', n: 'bus stop' },
    { c: '🚐', n: 'minibus' },
    { c: '🚑', n: 'ambulance' },
    { c: '🚒', n: 'fire engine' },
    { c: '🚓', n: 'police car' },
    { c: '🚔', n: 'oncoming police car' },
    { c: '🚕', n: 'taxi' },
    { c: '🚖', n: 'oncoming taxi' },
    { c: '🚗', n: 'automobile', k: 'car drive auto' },
    { c: '🚘', n: 'oncoming automobile' },
    { c: '🚙', n: 'recreational vehicle' },
    { c: '🚚', n: 'delivery truck' },
    { c: '🚛', n: 'articulated lorry' },
    { c: '🚜', n: 'tractor' },
    { c: '🚝', n: 'monorail' },
    { c: '🚞', n: 'mountain railway' },
    { c: '🚟', n: 'suspension railway' },
    { c: '🚠', n: 'mountain cableway' },
    { c: '🚡', n: 'aerial tramway' },
    { c: '🚢', n: 'ship' },
    { c: '🚣', n: 'rowboat' },
    { c: '🚤', n: 'speedboat' },
    { c: '🚥', n: 'horizontal traffic light' },
    { c: '🚦', n: 'vertical traffic light' },
    { c: '🚧', n: 'construction sign' },
    { c: '🚨', n: 'police cars revolving light', k: 'siren alert emergency urgent' },
    { c: '🚩', n: 'triangular flag on post' },
    { c: '🚪', n: 'door' },
    { c: '🚫', n: 'no entry sign' },
    { c: '🚬', n: 'smoking symbol' },
    { c: '🚭', n: 'no smoking symbol' },
    { c: '🚮', n: 'put litter in its place symbol' },
    { c: '🚯', n: 'do not litter symbol' },
    { c: '🚰', n: 'potable water symbol' },
    { c: '🚱', n: 'non-potable water symbol' },
    { c: '🚲', n: 'bicycle' },
    { c: '🚳', n: 'no bicycles' },
    { c: '🚴', n: 'bicyclist' },
    { c: '🚵', n: 'mountain bicyclist' },
    { c: '🚶', n: 'pedestrian' },
    { c: '🚷', n: 'no pedestrians' },
    { c: '🚸', n: 'children crossing' },
    { c: '🚹', n: 'mens symbol' },
    { c: '🚺', n: 'womens symbol' },
    { c: '🚻', n: 'restroom' },
    { c: '🚼', n: 'baby symbol' },
    { c: '🚽', n: 'toilet' },
    { c: '🚾', n: 'water closet' },
    { c: '🚿', n: 'shower' },
    { c: '🛀', n: 'bath' },
    { c: '🛁', n: 'bathtub' },
    { c: '🛂', n: 'passport control' },
    { c: '🛃', n: 'customs' },
    { c: '🛄', n: 'baggage claim' },
    { c: '🛅', n: 'left luggage' },
    { c: '🛆', n: 'triangle with rounded corners' },
    { c: '🛇', n: 'prohibited sign' },
    { c: '🛈', n: 'circled information source' },
    { c: '🛉', n: 'boys symbol' },
    { c: '🛊', n: 'girls symbol' },
    { c: '🛋', n: 'couch and lamp' },
    { c: '🛌', n: 'sleeping accommodation' },
    { c: '🛍', n: 'shopping bags' },
    { c: '🛎', n: 'bellhop bell' },
    { c: '🛏', n: 'bed' },
    { c: '🛐', n: 'place of worship' },
    { c: '🛑', n: 'octagonal sign', k: 'stop halt blocker' },
    { c: '🛒', n: 'shopping trolley' },
    { c: '🛓', n: 'stupa' },
    { c: '🛔', n: 'pagoda' },
    { c: '🛕', n: 'hindu temple' },
    { c: '🛖', n: 'hut' },
    { c: '🛗', n: 'elevator' },
    { c: '🛜', n: 'wireless' },
    { c: '🛝', n: 'playground slide' },
    { c: '🛞', n: 'wheel' },
    { c: '🛟', n: 'ring buoy' },
    { c: '🛠', n: 'hammer and wrench', k: 'tools fix repair build' },
    { c: '🛡', n: 'shield' },
    { c: '🛢', n: 'oil drum' },
    { c: '🛣', n: 'motorway' },
    { c: '🛤', n: 'railway track' },
    { c: '🛥', n: 'motor boat' },
    { c: '🛦', n: 'up-pointing military airplane' },
    { c: '🛧', n: 'up-pointing airplane' },
    { c: '🛨', n: 'up-pointing small airplane' },
    { c: '🛩', n: 'small airplane' },
    { c: '🛪', n: 'northeast-pointing airplane' },
    { c: '🛫', n: 'airplane departure' },
    { c: '🛬', n: 'airplane arriving' },
    { c: '🛰', n: 'satellite' },
    { c: '🛱', n: 'oncoming fire engine' },
    { c: '🛲', n: 'diesel locomotive' },
    { c: '🛳', n: 'passenger ship' },
    { c: '🛴', n: 'scooter' },
    { c: '🛵', n: 'motor scooter' },
    { c: '🛶', n: 'canoe' },
    { c: '🛷', n: 'sled' },
    { c: '🛸', n: 'flying saucer' },
    { c: '🛹', n: 'skateboard' },
    { c: '🛺', n: 'auto rickshaw' },
    { c: '🛻', n: 'pickup truck' },
    { c: '🛼', n: 'roller skate' },
    { c: '🟠', n: 'large orange circle' },
    { c: '🟡', n: 'large yellow circle' },
    { c: '🟢', n: 'large green circle' },
    { c: '🟣', n: 'large purple circle' },
    { c: '🟤', n: 'large brown circle' },
    { c: '🟥', n: 'large red square' },
    { c: '🟦', n: 'large blue square' },
    { c: '🟧', n: 'large orange square' },
    { c: '🟨', n: 'large yellow square' },
    { c: '🟩', n: 'large green square' },
    { c: '🟪', n: 'large purple square' },
    { c: '🟫', n: 'large brown square' },
    { c: '🤌', n: 'pinched fingers' },
    { c: '🤍', n: 'white heart' },
    { c: '🤎', n: 'brown heart' },
    { c: '🤏', n: 'pinching hand' },
    { c: '🤐', n: 'zipper-mouth face' },
    { c: '🤑', n: 'money-mouth face' },
    { c: '🤒', n: 'face with thermometer' },
    { c: '🤓', n: 'nerd face' },
    { c: '🤔', n: 'thinking face', k: 'think hmm' },
    { c: '🤕', n: 'face with head-bandage' },
    { c: '🤖', n: 'robot face', k: 'robot bot ai' },
    { c: '🤗', n: 'hugging face' },
    { c: '🤘', n: 'sign of the horns' },
    { c: '🤙', n: 'call me hand' },
    { c: '🤚', n: 'raised back of hand' },
    { c: '🤛', n: 'left-facing fist' },
    { c: '🤜', n: 'right-facing fist' },
    { c: '🤝', n: 'handshake', k: 'handshake deal agreement' },
    { c: '🤞', n: 'hand with index and middle fingers crossed' },
    { c: '🤟', n: 'i love you hand sign', k: 'loveyou ily rock horns' },
    { c: '🤠', n: 'face with cowboy hat' },
    { c: '🤡', n: 'clown face', k: 'clown joke' },
    { c: '🤢', n: 'nauseated face' },
    { c: '🤣', n: 'rolling on the floor laughing', k: 'rofl lol laughing' },
    { c: '🤤', n: 'drooling face' },
    { c: '🤥', n: 'lying face', k: 'lying liar pinocchio' },
    { c: '🤦', n: 'face palm' },
    { c: '🤧', n: 'sneezing face' },
    { c: '🤨', n: 'face with one eyebrow raised' },
    { c: '🤩', n: 'grinning face with star eyes' },
    { c: '🤪', n: 'grinning face with one large and one small eye' },
    { c: '🤫', n: 'face with finger covering closed lips' },
    { c: '🤬', n: 'serious face with symbols covering mouth' },
    { c: '🤭', n: 'smiling face with smiling eyes and hand covering mouth' },
    { c: '🤮', n: 'face with open mouth vomiting', k: 'sick vomit puke' },
    { c: '🤯', n: 'shocked face with exploding head' },
    { c: '🤰', n: 'pregnant woman' },
    { c: '🤱', n: 'breast-feeding' },
    { c: '🤲', n: 'palms up together' },
    { c: '🤳', n: 'selfie' },
    { c: '🤴', n: 'prince' },
    { c: '🤵', n: 'man in tuxedo' },
    { c: '🤶', n: 'mother christmas' },
    { c: '🤷', n: 'shrug' },
    { c: '🤸', n: 'person doing cartwheel' },
    { c: '🤹', n: 'juggling' },
    { c: '🤺', n: 'fencer' },
    { c: '🤻', n: 'modern pentathlon' },
    { c: '🤼', n: 'wrestlers' },
    { c: '🤽', n: 'water polo' },
    { c: '🤾', n: 'handball' },
    { c: '🤿', n: 'diving mask' },
    { c: '🥀', n: 'wilted flower' },
    { c: '🥁', n: 'drum with drumsticks' },
    { c: '🥂', n: 'clinking glasses' },
    { c: '🥃', n: 'tumbler glass' },
    { c: '🥄', n: 'spoon' },
    { c: '🥅', n: 'goal net' },
    { c: '🥆', n: 'rifle' },
    { c: '🥇', n: 'first place medal', k: 'gold first winner medal' },
    { c: '🥈', n: 'second place medal' },
    { c: '🥉', n: 'third place medal' },
    { c: '🥊', n: 'boxing glove' },
    { c: '🥋', n: 'martial arts uniform' },
    { c: '🥌', n: 'curling stone' },
    { c: '🥍', n: 'lacrosse stick and ball' },
    { c: '🥎', n: 'softball' },
    { c: '🥏', n: 'flying disc' },
    { c: '🥐', n: 'croissant' },
    { c: '🥑', n: 'avocado' },
    { c: '🥒', n: 'cucumber' },
    { c: '🥓', n: 'bacon' },
    { c: '🥔', n: 'potato' },
    { c: '🥕', n: 'carrot' },
    { c: '🥖', n: 'baguette bread' },
    { c: '🥗', n: 'green salad' },
    { c: '🥘', n: 'shallow pan of food' },
    { c: '🥙', n: 'stuffed flatbread' },
    { c: '🥚', n: 'egg' },
    { c: '🥛', n: 'glass of milk' },
    { c: '🥜', n: 'peanuts' },
    { c: '🥝', n: 'kiwifruit' },
    { c: '🥞', n: 'pancakes' },
    { c: '🥟', n: 'dumpling' },
    { c: '🥠', n: 'fortune cookie' },
    { c: '🥡', n: 'takeout box' },
    { c: '🥢', n: 'chopsticks' },
    { c: '🥣', n: 'bowl with spoon' },
    { c: '🥤', n: 'cup with straw' },
    { c: '🥥', n: 'coconut' },
    { c: '🥦', n: 'broccoli' },
    { c: '🥧', n: 'pie' },
    { c: '🥨', n: 'pretzel' },
    { c: '🥩', n: 'cut of meat' },
    { c: '🥪', n: 'sandwich' },
    { c: '🥫', n: 'canned food' },
    { c: '🥬', n: 'leafy green' },
    { c: '🥭', n: 'mango' },
    { c: '🥮', n: 'moon cake' },
    { c: '🥯', n: 'bagel' },
    { c: '🥰', n: 'smiling face with smiling eyes and three hearts' },
    { c: '🥱', n: 'yawning face', k: 'yawn bored' },
    { c: '🥲', n: 'smiling face with tear' },
    { c: '🥳', n: 'face with party horn and party hat' },
    { c: '🥴', n: 'face with uneven eyes and wavy mouth' },
    { c: '🥵', n: 'overheated face' },
    { c: '🥶', n: 'freezing face' },
    { c: '🥷', n: 'ninja' },
    { c: '🥸', n: 'disguised face' },
    { c: '🥹', n: 'face holding back tears' },
    { c: '🥺', n: 'face with pleading eyes' },
    { c: '🥻', n: 'sari' },
    { c: '🥼', n: 'lab coat' },
    { c: '🥽', n: 'goggles' },
    { c: '🥾', n: 'hiking boot' },
    { c: '🥿', n: 'flat shoe' },
    { c: '🦀', n: 'crab' },
    { c: '🦁', n: 'lion face' },
    { c: '🦂', n: 'scorpion' },
    { c: '🦃', n: 'turkey' },
    { c: '🦄', n: 'unicorn face' },
    { c: '🦅', n: 'eagle' },
    { c: '🦆', n: 'duck' },
    { c: '🦇', n: 'bat' },
    { c: '🦈', n: 'shark' },
    { c: '🦉', n: 'owl' },
    { c: '🦊', n: 'fox face' },
    { c: '🦋', n: 'butterfly' },
    { c: '🦌', n: 'deer' },
    { c: '🦍', n: 'gorilla' },
    { c: '🦎', n: 'lizard' },
    { c: '🦏', n: 'rhinoceros' },
    { c: '🦐', n: 'shrimp' },
    { c: '🦑', n: 'squid' },
    { c: '🦒', n: 'giraffe face' },
    { c: '🦓', n: 'zebra face' },
    { c: '🦔', n: 'hedgehog' },
    { c: '🦕', n: 'sauropod' },
    { c: '🦖', n: 't-rex' },
    { c: '🦗', n: 'cricket' },
    { c: '🦘', n: 'kangaroo' },
    { c: '🦙', n: 'llama' },
    { c: '🦚', n: 'peacock' },
    { c: '🦛', n: 'hippopotamus' },
    { c: '🦜', n: 'parrot' },
    { c: '🦝', n: 'raccoon' },
    { c: '🦞', n: 'lobster' },
    { c: '🦟', n: 'mosquito' },
    { c: '🦠', n: 'microbe' },
    { c: '🦡', n: 'badger' },
    { c: '🦢', n: 'swan' },
    { c: '🦣', n: 'mammoth' },
    { c: '🦤', n: 'dodo' },
    { c: '🦥', n: 'sloth' },
    { c: '🦦', n: 'otter' },
    { c: '🦧', n: 'orangutan' },
    { c: '🦨', n: 'skunk' },
    { c: '🦩', n: 'flamingo' },
    { c: '🦪', n: 'oyster' },
    { c: '🦫', n: 'beaver' },
    { c: '🦬', n: 'bison' },
    { c: '🦭', n: 'seal' },
    { c: '🦮', n: 'guide dog' },
    { c: '🦯', n: 'probing cane' },
    { c: '🦴', n: 'bone' },
    { c: '🦵', n: 'leg' },
    { c: '🦶', n: 'foot' },
    { c: '🦷', n: 'tooth' },
    { c: '🦸', n: 'superhero' },
    { c: '🦹', n: 'supervillain' },
    { c: '🦺', n: 'safety vest' },
    { c: '🦻', n: 'ear with hearing aid' },
    { c: '🦼', n: 'motorized wheelchair' },
    { c: '🦽', n: 'manual wheelchair' },
    { c: '🦾', n: 'mechanical arm' },
    { c: '🦿', n: 'mechanical leg' },
    { c: '🧀', n: 'cheese wedge' },
    { c: '🧁', n: 'cupcake' },
    { c: '🧂', n: 'salt shaker' },
    { c: '🧃', n: 'beverage box' },
    { c: '🧄', n: 'garlic' },
    { c: '🧅', n: 'onion' },
    { c: '🧆', n: 'falafel' },
    { c: '🧇', n: 'waffle' },
    { c: '🧈', n: 'butter' },
    { c: '🧉', n: 'mate drink' },
    { c: '🧊', n: 'ice cube' },
    { c: '🧋', n: 'bubble tea' },
    { c: '🧌', n: 'troll' },
    { c: '🧍', n: 'standing person' },
    { c: '🧎', n: 'kneeling person' },
    { c: '🧏', n: 'deaf person' },
    { c: '🧐', n: 'face with monocle' },
    { c: '🧑', n: 'adult' },
    { c: '🧒', n: 'child' },
    { c: '🧓', n: 'older adult' },
    { c: '🧔', n: 'bearded person' },
    { c: '🧕', n: 'person with headscarf' },
    { c: '🧖', n: 'person in steamy room' },
    { c: '🧗', n: 'person climbing' },
    { c: '🧘', n: 'person in lotus position' },
    { c: '🧙', n: 'mage' },
    { c: '🧚', n: 'fairy' },
    { c: '🧛', n: 'vampire' },
    { c: '🧜', n: 'merperson' },
    { c: '🧝', n: 'elf' },
    { c: '🧞', n: 'genie' },
    { c: '🧟', n: 'zombie' },
    { c: '🧠', n: 'brain', k: 'brain smart mind' },
    { c: '🧡', n: 'orange heart' },
    { c: '🧢', n: 'billed cap' },
    { c: '🧣', n: 'scarf' },
    { c: '🧤', n: 'gloves' },
    { c: '🧥', n: 'coat' },
    { c: '🧦', n: 'socks' },
    { c: '🧧', n: 'red gift envelope' },
    { c: '🧨', n: 'firecracker' },
    { c: '🧩', n: 'jigsaw puzzle piece' },
    { c: '🧪', n: 'test tube' },
    { c: '🧫', n: 'petri dish' },
    { c: '🧬', n: 'dna double helix' },
    { c: '🧭', n: 'compass' },
    { c: '🧮', n: 'abacus' },
    { c: '🧯', n: 'fire extinguisher' },
    { c: '🧰', n: 'toolbox' },
    { c: '🧱', n: 'brick' },
    { c: '🧲', n: 'magnet' },
    { c: '🧳', n: 'luggage' },
    { c: '🧴', n: 'lotion bottle' },
    { c: '🧵', n: 'spool of thread' },
    { c: '🧶', n: 'ball of yarn' },
    { c: '🧷', n: 'safety pin' },
    { c: '🧸', n: 'teddy bear' },
    { c: '🧹', n: 'broom' },
    { c: '🧺', n: 'basket' },
    { c: '🧻', n: 'roll of paper' },
    { c: '🧼', n: 'bar of soap' },
    { c: '🧽', n: 'sponge' },
    { c: '🧾', n: 'receipt' },
    { c: '🧿', n: 'nazar amulet' },
    { c: '🩰', n: 'ballet shoes' },
    { c: '🩱', n: 'one-piece swimsuit' },
    { c: '🩲', n: 'briefs' },
    { c: '🩳', n: 'shorts' },
    { c: '🩴', n: 'thong sandal' },
    { c: '🩵', n: 'light blue heart' },
    { c: '🩶', n: 'grey heart' },
    { c: '🩷', n: 'pink heart' },
    { c: '🩸', n: 'drop of blood' },
    { c: '🩹', n: 'adhesive bandage' },
    { c: '🩺', n: 'stethoscope' },
    { c: '🩻', n: 'x-ray' },
    { c: '🩼', n: 'crutch' },
    { c: '🪀', n: 'yo-yo' },
    { c: '🪁', n: 'kite' },
    { c: '🪂', n: 'parachute' },
    { c: '🪃', n: 'boomerang' },
    { c: '🪄', n: 'magic wand' },
    { c: '🪅', n: 'pinata' },
    { c: '🪆', n: 'nesting dolls' },
    { c: '🪇', n: 'maracas' },
    { c: '🪈', n: 'flute' },
    { c: '🪉', n: 'harp' },
    { c: '🪏', n: 'shovel' },
    { c: '🪐', n: 'ringed planet' },
    { c: '🪑', n: 'chair' },
    { c: '🪒', n: 'razor' },
    { c: '🪓', n: 'axe' },
    { c: '🪔', n: 'diya lamp' },
    { c: '🪕', n: 'banjo' },
    { c: '🪖', n: 'military helmet' },
    { c: '🪗', n: 'accordion' },
    { c: '🪘', n: 'long drum' },
    { c: '🪙', n: 'coin' },
    { c: '🪚', n: 'carpentry saw' },
    { c: '🪛', n: 'screwdriver' },
    { c: '🪜', n: 'ladder' },
    { c: '🪝', n: 'hook' },
    { c: '🪞', n: 'mirror' },
    { c: '🪟', n: 'window' },
    { c: '🪠', n: 'plunger' },
    { c: '🪡', n: 'sewing needle' },
    { c: '🪢', n: 'knot' },
    { c: '🪣', n: 'bucket' },
    { c: '🪤', n: 'mouse trap' },
    { c: '🪥', n: 'toothbrush' },
    { c: '🪦', n: 'headstone' },
    { c: '🪧', n: 'placard' },
    { c: '🪨', n: 'rock' },
    { c: '🪩', n: 'mirror ball' },
    { c: '🪪', n: 'identification card' },
    { c: '🪫', n: 'low battery' },
    { c: '🪬', n: 'hamsa' },
    { c: '🪭', n: 'folding hand fan' },
    { c: '🪮', n: 'hair pick' },
    { c: '🪯', n: 'khanda' },
    { c: '🪰', n: 'fly' },
    { c: '🪱', n: 'worm' },
    { c: '🪲', n: 'beetle' },
    { c: '🪳', n: 'cockroach' },
    { c: '🪴', n: 'potted plant' },
    { c: '🪵', n: 'wood' },
    { c: '🪶', n: 'feather' },
    { c: '🪷', n: 'lotus' },
    { c: '🪸', n: 'coral' },
    { c: '🪹', n: 'empty nest' },
    { c: '🪺', n: 'nest with eggs' },
    { c: '🪻', n: 'hyacinth' },
    { c: '🪼', n: 'jellyfish' },
    { c: '🪽', n: 'wing' },
    { c: '🪾', n: 'leafless tree' },
    { c: '🪿', n: 'goose' },
    { c: '🫀', n: 'anatomical heart' },
    { c: '🫁', n: 'lungs' },
    { c: '🫂', n: 'people hugging' },
    { c: '🫃', n: 'pregnant man' },
    { c: '🫄', n: 'pregnant person' },
    { c: '🫅', n: 'person with crown' },
    { c: '🫆', n: 'fingerprint' },
    { c: '🫎', n: 'moose' },
    { c: '🫏', n: 'donkey' },
    { c: '🫐', n: 'blueberries' },
    { c: '🫑', n: 'bell pepper' },
    { c: '🫒', n: 'olive' },
    { c: '🫓', n: 'flatbread' },
    { c: '🫔', n: 'tamale' },
    { c: '🫕', n: 'fondue' },
    { c: '🫖', n: 'teapot' },
    { c: '🫗', n: 'pouring liquid' },
    { c: '🫘', n: 'beans' },
    { c: '🫙', n: 'jar' },
    { c: '🫚', n: 'ginger root' },
    { c: '🫛', n: 'pea pod' },
    { c: '🫜', n: 'root vegetable' },
    { c: '🫟', n: 'splatter' },
    { c: '🫠', n: 'melting face' },
    { c: '🫡', n: 'saluting face', k: 'salute' },
    { c: '🫢', n: 'face with open eyes and hand over mouth' },
    { c: '🫣', n: 'face with peeking eye' },
    { c: '🫤', n: 'face with diagonal mouth' },
    { c: '🫥', n: 'dotted line face' },
    { c: '🫦', n: 'biting lip' },
    { c: '🫧', n: 'bubbles' },
    { c: '🫨', n: 'shaking face' },
    { c: '🫩', n: 'face with bags under eyes' },
    { c: '🫰', n: 'hand with index finger and thumb crossed' },
    { c: '🫱', n: 'rightwards hand' },
    { c: '🫲', n: 'leftwards hand' },
    { c: '🫳', n: 'palm down hand' },
    { c: '🫴', n: 'palm up hand' },
    { c: '🫵', n: 'index pointing at the viewer' },
    { c: '🫶', n: 'heart hands' },
    { c: '🫷', n: 'leftwards pushing hand' },
    { c: '🫸', n: 'rightwards pushing hand' },
    { c: '©️', n: 'copyright sign' },
    { c: '®️', n: 'registered sign' },
    { c: '‼️', n: 'double exclamation mark' },
    { c: '⁉️', n: 'exclamation question mark' },
    { c: '™️', n: 'trade mark sign' },
    { c: 'ℹ️', n: 'information source' },
    { c: '↔️', n: 'left right arrow' },
    { c: '↕️', n: 'up down arrow' },
    { c: '↖️', n: 'north west arrow' },
    { c: '↗️', n: 'north east arrow' },
    { c: '↘️', n: 'south east arrow' },
    { c: '↙️', n: 'south west arrow' },
    { c: '↩️', n: 'leftwards arrow with hook' },
    { c: '↪️', n: 'rightwards arrow with hook' },
    { c: '⌚', n: 'watch' },
    { c: '⌛', n: 'hourglass' },
    { c: '⌨️', n: 'keyboard' },
    { c: '⏏️', n: 'eject symbol' },
    { c: '⏩', n: 'black right-pointing double triangle' },
    { c: '⏪', n: 'black left-pointing double triangle' },
    { c: '⏫', n: 'black up-pointing double triangle' },
    { c: '⏬', n: 'black down-pointing double triangle' },
    { c: '⏭️', n: 'black right-pointing double triangle with vertical bar' },
    { c: '⏮️', n: 'black left-pointing double triangle with vertical bar' },
    { c: '⏯️', n: 'black right-pointing triangle with double vertical bar' },
    { c: '⏰', n: 'alarm clock', k: 'alarm clock time' },
    { c: '⏱️', n: 'stopwatch' },
    { c: '⏲️', n: 'timer clock' },
    { c: '⏳', n: 'hourglass with flowing sand' },
    { c: '⏸️', n: 'double vertical bar' },
    { c: '⏹️', n: 'black square for stop' },
    { c: '⏺️', n: 'black circle for record' },
    { c: 'Ⓜ️', n: 'circled latin capital letter m' },
    { c: '▪️', n: 'black small square' },
    { c: '▫️', n: 'white small square' },
    { c: '▶️', n: 'black right-pointing triangle' },
    { c: '◀️', n: 'black left-pointing triangle' },
    { c: '◻️', n: 'white medium square' },
    { c: '◼️', n: 'black medium square' },
    { c: '◽', n: 'white medium small square' },
    { c: '◾', n: 'black medium small square' },
    { c: '☀️', n: 'black sun with rays' },
    { c: '☁️', n: 'cloud' },
    { c: '☂️', n: 'umbrella' },
    { c: '☃️', n: 'snowman' },
    { c: '☄️', n: 'comet' },
    { c: '☎️', n: 'black telephone' },
    { c: '☑️', n: 'ballot box with check' },
    { c: '☔', n: 'umbrella with rain drops' },
    { c: '☕', n: 'hot beverage', k: 'coffee tea drink' },
    { c: '☘️', n: 'shamrock' },
    { c: '☝️', n: 'white up pointing index' },
    { c: '☠️', n: 'skull and crossbones' },
    { c: '☢️', n: 'radioactive sign' },
    { c: '☣️', n: 'biohazard sign' },
    { c: '☦️', n: 'orthodox cross' },
    { c: '☪️', n: 'star and crescent' },
    { c: '☮️', n: 'peace symbol' },
    { c: '☯️', n: 'yin yang' },
    { c: '☸️', n: 'wheel of dharma' },
    { c: '☹️', n: 'white frowning face' },
    { c: '☺️', n: 'white smiling face' },
    { c: '♀️', n: 'female sign' },
    { c: '♂️', n: 'male sign' },
    { c: '♈️', n: 'aries' },
    { c: '♉️', n: 'taurus' },
    { c: '♊️', n: 'gemini' },
    { c: '♋️', n: 'cancer' },
    { c: '♌️', n: 'leo' },
    { c: '♍️', n: 'virgo' },
    { c: '♎️', n: 'libra' },
    { c: '♏️', n: 'scorpius' },
    { c: '♐️', n: 'sagittarius' },
    { c: '♑️', n: 'capricorn' },
    { c: '♒️', n: 'aquarius' },
    { c: '♓️', n: 'pisces' },
    { c: '♟️', n: 'black chess pawn' },
    { c: '♠️', n: 'black spade suit' },
    { c: '♣️', n: 'black club suit' },
    { c: '♥️', n: 'black heart suit' },
    { c: '♦️', n: 'black diamond suit' },
    { c: '♨️', n: 'hot springs' },
    { c: '♻️', n: 'black universal recycling symbol' },
    { c: '♾️', n: 'permanent paper sign' },
    { c: '♿', n: 'wheelchair symbol' },
    { c: '⚒️', n: 'hammer and pick' },
    { c: '⚓', n: 'anchor' },
    { c: '⚔️', n: 'crossed swords' },
    { c: '⚕️', n: 'staff of aesculapius' },
    { c: '⚖️', n: 'scales' },
    { c: '⚗️', n: 'alembic' },
    { c: '⚙️', n: 'gear', k: 'settings gear config cog' },
    { c: '⚛️', n: 'atom symbol' },
    { c: '⚜️', n: 'fleur-de-lis' },
    { c: '⚠️', n: 'warning sign', k: 'warning caution alert' },
    { c: '⚡', n: 'high voltage sign' },
    { c: '⚧️', n: 'male with stroke and male and female sign' },
    { c: '⚪', n: 'medium white circle' },
    { c: '⚫', n: 'medium black circle' },
    { c: '⚰️', n: 'coffin' },
    { c: '⚱️', n: 'funeral urn' },
    { c: '⚽', n: 'soccer ball', k: 'soccer football ball' },
    { c: '⚾', n: 'baseball' },
    { c: '⛄', n: 'snowman without snow' },
    { c: '⛅', n: 'sun behind cloud' },
    { c: '⛈️', n: 'thunder cloud and rain' },
    { c: '⛎', n: 'ophiuchus' },
    { c: '⛏️', n: 'pick' },
    { c: '⛑️', n: 'helmet with white cross' },
    { c: '⛓️', n: 'chains' },
    { c: '⛔', n: 'no entry' },
    { c: '⛩️', n: 'shinto shrine' },
    { c: '⛪', n: 'church' },
    { c: '⛰️', n: 'mountain' },
    { c: '⛱️', n: 'umbrella on ground' },
    { c: '⛲', n: 'fountain' },
    { c: '⛳', n: 'flag in hole' },
    { c: '⛴️', n: 'ferry' },
    { c: '⛵', n: 'sailboat' },
    { c: '⛷️', n: 'skier' },
    { c: '⛸️', n: 'ice skate' },
    { c: '⛹️', n: 'person with ball' },
    { c: '⛺', n: 'tent' },
    { c: '⛽', n: 'fuel pump' },
    { c: '✂️', n: 'black scissors' },
    { c: '✅', n: 'white heavy check mark', k: 'check done tick yes complete' },
    { c: '✈️', n: 'airplane', k: 'plane flight travel fly' },
    { c: '✉️', n: 'envelope' },
    { c: '✊', n: 'raised fist' },
    { c: '✋', n: 'raised hand' },
    { c: '✌️', n: 'victory hand' },
    { c: '✍️', n: 'writing hand', k: 'write writing pen' },
    { c: '✏️', n: 'pencil' },
    { c: '✒️', n: 'black nib' },
    { c: '✔️', n: 'heavy check mark' },
    { c: '✖️', n: 'heavy multiplication x' },
    { c: '✝️', n: 'latin cross' },
    { c: '✡️', n: 'star of david' },
    { c: '✨', n: 'sparkles' },
    { c: '✳️', n: 'eight spoked asterisk' },
    { c: '✴️', n: 'eight pointed black star' },
    { c: '❄️', n: 'snowflake' },
    { c: '❇️', n: 'sparkle' },
    { c: '❌', n: 'cross mark', k: 'x no wrong fail cross' },
    { c: '❎', n: 'negative squared cross mark' },
    { c: '❓', n: 'black question mark ornament' },
    { c: '❔', n: 'white question mark ornament' },
    { c: '❕', n: 'white exclamation mark ornament' },
    { c: '❗', n: 'heavy exclamation mark symbol' },
    { c: '❣️', n: 'heavy heart exclamation mark ornament' },
    { c: '❤️', n: 'heavy black heart', k: 'love heart red' },
    { c: '➕', n: 'heavy plus sign' },
    { c: '➖', n: 'heavy minus sign' },
    { c: '➗', n: 'heavy division sign' },
    { c: '➡️', n: 'black rightwards arrow' },
    { c: '➰', n: 'curly loop' },
    { c: '➿', n: 'double curly loop' },
    { c: '⤴️', n: 'arrow pointing rightwards then curving upwards' },
    { c: '⤵️', n: 'arrow pointing rightwards then curving downwards' },
    { c: '⬅️', n: 'leftwards black arrow' },
    { c: '⬆️', n: 'upwards black arrow' },
    { c: '⬇️', n: 'downwards black arrow' },
    { c: '⬛', n: 'black large square' },
    { c: '⬜', n: 'white large square' },
    { c: '⭐', n: 'white medium star', k: 'star favorite' },
    { c: '⭕', n: 'heavy large circle' },
    { c: '〰️', n: 'wavy dash' },
    { c: '〽️', n: 'part alternation mark' },
    { c: '㊗️', n: 'circled ideograph congratulation' },
    { c: '㊙️', n: 'circled ideograph secret' },
    { c: '🀄', n: 'mahjong tile red dragon' },
    { c: '🃏', n: 'playing card black joker' },
    { c: '🅰️', n: 'negative squared latin capital letter a' },
    { c: '🅱️', n: 'negative squared latin capital letter b' },
    { c: '🅾️', n: 'negative squared latin capital letter o' },
    { c: '🅿️', n: 'negative squared latin capital letter p' },
    { c: '🆎', n: 'negative squared ab' },
    { c: '🆑', n: 'squared cl' },
    { c: '🆒', n: 'squared cool' },
    { c: '🆓', n: 'squared free' },
    { c: '🆔', n: 'squared id' },
    { c: '🆕', n: 'squared new' },
    { c: '🆖', n: 'squared ng' },
    { c: '🆗', n: 'squared ok' },
    { c: '🆘', n: 'squared sos' },
    { c: '🆙', n: 'squared up with exclamation mark' },
    { c: '🆚', n: 'squared vs' },
    { c: '🈁', n: 'squared katakana koko' },
    { c: '🈂️', n: 'squared katakana sa' },
    { c: '🈚', n: 'squared cjk unified ideograph-7121' },
    { c: '🈯', n: 'squared cjk unified ideograph-6307' },
    { c: '🈲', n: 'squared cjk unified ideograph-7981' },
    { c: '🈳', n: 'squared cjk unified ideograph-7a7a' },
    { c: '🈴', n: 'squared cjk unified ideograph-5408' },
    { c: '🈵', n: 'squared cjk unified ideograph-6e80' },
    { c: '🈶', n: 'squared cjk unified ideograph-6709' },
    { c: '🈷️', n: 'squared cjk unified ideograph-6708' },
    { c: '🈸', n: 'squared cjk unified ideograph-7533' },
    { c: '🈹', n: 'squared cjk unified ideograph-5272' },
    { c: '🈺', n: 'squared cjk unified ideograph-55b6' },
    { c: '🉐', n: 'circled ideograph advantage' },
    { c: '🉑', n: 'circled ideograph accept' },

    // ─── Keycap sequences (2026-07-30) ─────────────────────────────
    // Multi-codepoint: base + U+FE0F U+20E3. The single-codepoint
    // table above cannot represent these.
    { c: '#️⃣', n: 'keycap number sign', k: '# hash pound' },
    { c: '*️⃣', n: 'keycap asterisk', k: '* star multiply' },
    { c: '0️⃣', n: 'keycap zero', k: '0 zero' },
    { c: '1️⃣', n: 'keycap one', k: '1 one' },
    { c: '2️⃣', n: 'keycap two', k: '2 two' },
    { c: '3️⃣', n: 'keycap three', k: '3 three' },
    { c: '4️⃣', n: 'keycap four', k: '4 four' },
    { c: '5️⃣', n: 'keycap five', k: '5 five' },
    { c: '6️⃣', n: 'keycap six', k: '6 six' },
    { c: '7️⃣', n: 'keycap seven', k: '7 seven' },
    { c: '8️⃣', n: 'keycap eight', k: '8 eight' },
    { c: '9️⃣', n: 'keycap nine', k: '9 nine' },

    // ─── ZWJ sequences (2026-07-30) ────────────────────────────────
    // Professions, hair variants, couples, families and the popular
    // misc joins. Base forms (bearded person, person with blond
    // hair, family) already exist above as single codepoints.
    { c: '🧑‍⚕️', n: 'person health worker', k: 'doctor nurse medic' },
    { c: '🧑‍🎓', n: 'person student', k: 'graduate' },
    { c: '🧑‍🏫', n: 'person teacher', k: 'professor' },
    { c: '🧑‍⚖️', n: 'person judge', k: 'lawyer justice court' },
    { c: '🧑‍🌾', n: 'person farmer', k: 'agriculture rancher' },
    { c: '🧑‍🍳', n: 'person cook', k: 'chef kitchen' },
    { c: '🧑‍🔧', n: 'person mechanic', k: 'plumber electrician tradesperson' },
    { c: '🧑‍🏭', n: 'person factory worker', k: 'welder industry' },
    { c: '🧑‍💼', n: 'person office worker', k: 'business manager' },
    { c: '🧑‍🔬', n: 'person scientist', k: 'chemist researcher' },
    { c: '🧑‍💻', n: 'person technologist', k: 'developer coder programmer software engineer computer' },
    { c: '🧑‍🎤', n: 'person singer', k: 'musician vocalist' },
    { c: '🧑‍🎨', n: 'person artist', k: 'painter' },
    { c: '🧑‍✈️', n: 'person pilot', k: 'aviator plane' },
    { c: '🧑‍🚒', n: 'person firefighter', k: 'fireman fire' },
    { c: '🧑‍🚀', n: 'person astronaut', k: 'cosmonaut space' },
    { c: '👨‍⚕️', n: 'man health worker', k: 'doctor nurse medic' },
    { c: '👨‍🎓', n: 'man student', k: 'graduate' },
    { c: '👨‍🏫', n: 'man teacher', k: 'professor' },
    { c: '👨‍⚖️', n: 'man judge', k: 'lawyer justice court' },
    { c: '👨‍🌾', n: 'man farmer', k: 'agriculture rancher' },
    { c: '👨‍🍳', n: 'man cook', k: 'chef kitchen' },
    { c: '👨‍🔧', n: 'man mechanic', k: 'plumber electrician tradesperson' },
    { c: '👨‍🏭', n: 'man factory worker', k: 'welder industry' },
    { c: '👨‍💼', n: 'man office worker', k: 'business manager' },
    { c: '👨‍🔬', n: 'man scientist', k: 'chemist researcher' },
    { c: '👨‍💻', n: 'man technologist', k: 'developer coder programmer software engineer computer' },
    { c: '👨‍🎤', n: 'man singer', k: 'musician vocalist' },
    { c: '👨‍🎨', n: 'man artist', k: 'painter' },
    { c: '👨‍✈️', n: 'man pilot', k: 'aviator plane' },
    { c: '👨‍🚒', n: 'man firefighter', k: 'fireman fire' },
    { c: '👨‍🚀', n: 'man astronaut', k: 'cosmonaut space' },
    { c: '👩‍⚕️', n: 'woman health worker', k: 'doctor nurse medic' },
    { c: '👩‍🎓', n: 'woman student', k: 'graduate' },
    { c: '👩‍🏫', n: 'woman teacher', k: 'professor' },
    { c: '👩‍⚖️', n: 'woman judge', k: 'lawyer justice court' },
    { c: '👩‍🌾', n: 'woman farmer', k: 'agriculture rancher' },
    { c: '👩‍🍳', n: 'woman cook', k: 'chef kitchen' },
    { c: '👩‍🔧', n: 'woman mechanic', k: 'plumber electrician tradesperson' },
    { c: '👩‍🏭', n: 'woman factory worker', k: 'welder industry' },
    { c: '👩‍💼', n: 'woman office worker', k: 'business manager' },
    { c: '👩‍🔬', n: 'woman scientist', k: 'chemist researcher' },
    { c: '👩‍💻', n: 'woman technologist', k: 'developer coder programmer software engineer computer' },
    { c: '👩‍🎤', n: 'woman singer', k: 'musician vocalist' },
    { c: '👩‍🎨', n: 'woman artist', k: 'painter' },
    { c: '👩‍✈️', n: 'woman pilot', k: 'aviator plane' },
    { c: '👩‍🚒', n: 'woman firefighter', k: 'fireman fire' },
    { c: '👩‍🚀', n: 'woman astronaut', k: 'cosmonaut space' },
    { c: '🧑‍🦰', n: 'person red hair', k: 'redhead ginger' },
    { c: '👨‍🦰', n: 'man red hair', k: 'redhead ginger' },
    { c: '👩‍🦰', n: 'woman red hair', k: 'redhead ginger' },
    { c: '🧑‍🦱', n: 'person curly hair', k: 'afro' },
    { c: '👨‍🦱', n: 'man curly hair', k: 'afro' },
    { c: '👩‍🦱', n: 'woman curly hair', k: 'afro' },
    { c: '🧑‍🦳', n: 'person white hair', k: 'gray hair elderly' },
    { c: '👨‍🦳', n: 'man white hair', k: 'gray hair elderly' },
    { c: '👩‍🦳', n: 'woman white hair', k: 'gray hair elderly' },
    { c: '🧑‍🦲', n: 'person bald', k: 'shaved' },
    { c: '👨‍🦲', n: 'man bald', k: 'shaved' },
    { c: '👩‍🦲', n: 'woman bald', k: 'shaved' },
    { c: '🧑‍🍼', n: 'person feeding baby', k: 'parent bottle' },
    { c: '👨‍🍼', n: 'man feeding baby', k: 'father bottle' },
    { c: '👩‍🍼', n: 'woman feeding baby', k: 'mother bottle' },
    { c: '🧑‍🎄', n: 'mx claus', k: 'santa christmas' },
    { c: '🧑‍🤝‍🧑', n: 'people holding hands', k: 'friends couple' },
    { c: '👩‍❤️‍👨', n: 'couple with heart woman man', k: 'love' },
    { c: '👩‍❤️‍💋‍👨', n: 'kiss woman man', k: 'couple' },
    { c: '👨‍👩‍👦', n: 'family man woman boy' },
    { c: '👨‍👩‍👧', n: 'family man woman girl' },
    { c: '👨‍👩‍👧‍👦', n: 'family man woman girl boy' },
    { c: '👨‍👩‍👦‍👦', n: 'family man woman boy boy' },
    { c: '👨‍👩‍👧‍👧', n: 'family man woman girl girl' },
    { c: '👨‍👦', n: 'family man boy', k: 'single father' },
    { c: '👨‍👧', n: 'family man girl', k: 'single father' },
    { c: '👨‍👦‍👦', n: 'family man boy boy' },
    { c: '👨‍👧‍👦', n: 'family man girl boy' },
    { c: '👨‍👧‍👧', n: 'family man girl girl' },
    { c: '👩‍👦', n: 'family woman boy', k: 'single mother' },
    { c: '👩‍👧', n: 'family woman girl', k: 'single mother' },
    { c: '👩‍👦‍👦', n: 'family woman boy boy' },
    { c: '👩‍👧‍👦', n: 'family woman girl boy' },
    { c: '👩‍👧‍👧', n: 'family woman girl girl' },
    { c: '🏴‍☠️', n: 'pirate flag', k: 'jolly roger' },
    { c: '🐕‍🦺', n: 'service dog', k: 'assistance dog' },
    { c: '🐈‍⬛', n: 'black cat', k: 'unlucky halloween' },
    { c: '❤️‍🔥', n: 'heart on fire', k: 'burning love passion' },
    { c: '❤️‍🩹', n: 'mending heart', k: 'healing recovering' },
    { c: '👁️‍🗨️', n: 'eye in speech bubble', k: 'witness anti bullying' },
    { c: '🧔‍♂️', n: 'man beard', k: 'bearded' },
    { c: '🧔‍♀️', n: 'woman beard', k: 'bearded' },
    { c: '👱‍♀️', n: 'woman blond hair', k: 'blonde' },
    { c: '👱‍♂️', n: 'man blond hair', k: 'blonde' },
    { c: '🍄‍🟫', n: 'brown mushroom', k: 'porcini' },
    { c: '🐦‍⬛', n: 'black bird', k: 'crow raven' },
    { c: '🐦‍🔥', n: 'phoenix', k: 'firebird rebirth' },

    // ─── Flags (2026-07-30) ────────────────────────────────────────
    // ISO 3166-1 alpha-2 → regional indicator pairs. Note: Windows
    // renders these as letter pairs (Segoe UI Emoji has no flag
    // glyphs) — same as the OS emoji panel; the copied text is a
    // correct flag sequence on every other platform.
    { c: '🇦🇩', n: 'flag andorra', k: 'ad flag' },
    { c: '🇦🇪', n: 'flag united arab emirates', k: 'ae emirates dubai abu dhabi flag' },
    { c: '🇦🇫', n: 'flag afghanistan', k: 'af flag' },
    { c: '🇦🇬', n: 'flag antigua and barbuda', k: 'ag flag' },
    { c: '🇦🇮', n: 'flag anguilla', k: 'ai flag' },
    { c: '🇦🇱', n: 'flag albania', k: 'al flag' },
    { c: '🇦🇲', n: 'flag armenia', k: 'am flag' },
    { c: '🇦🇴', n: 'flag angola', k: 'ao flag' },
    { c: '🇦🇶', n: 'flag antarctica', k: 'aq flag' },
    { c: '🇦🇷', n: 'flag argentina', k: 'ar flag' },
    { c: '🇦🇸', n: 'flag american samoa', k: 'as flag' },
    { c: '🇦🇹', n: 'flag austria', k: 'at flag' },
    { c: '🇦🇺', n: 'flag australia', k: 'au flag' },
    { c: '🇦🇼', n: 'flag aruba', k: 'aw flag' },
    { c: '🇦🇽', n: 'flag aland islands', k: 'ax aland finland flag' },
    { c: '🇦🇿', n: 'flag azerbaijan', k: 'az flag' },
    { c: '🇧🇦', n: 'flag bosnia and herzegovina', k: 'ba bosnia herzegovina flag' },
    { c: '🇧🇧', n: 'flag barbados', k: 'bb flag' },
    { c: '🇧🇩', n: 'flag bangladesh', k: 'bd flag' },
    { c: '🇧🇪', n: 'flag belgium', k: 'be flag' },
    { c: '🇧🇫', n: 'flag burkina faso', k: 'bf flag' },
    { c: '🇧🇬', n: 'flag bulgaria', k: 'bg flag' },
    { c: '🇧🇭', n: 'flag bahrain', k: 'bh flag' },
    { c: '🇧🇮', n: 'flag burundi', k: 'bi flag' },
    { c: '🇧🇯', n: 'flag benin', k: 'bj flag' },
    { c: '🇧🇱', n: 'flag saint barthelemy', k: 'bl st barts flag' },
    { c: '🇧🇲', n: 'flag bermuda', k: 'bm flag' },
    { c: '🇧🇳', n: 'flag brunei', k: 'bn flag' },
    { c: '🇧🇴', n: 'flag bolivia', k: 'bo flag' },
    { c: '🇧🇶', n: 'flag bonaire', k: 'bq sint eustatius saba caribbean netherlands flag' },
    { c: '🇧🇷', n: 'flag brazil', k: 'br flag' },
    { c: '🇧🇸', n: 'flag bahamas', k: 'bs flag' },
    { c: '🇧🇹', n: 'flag bhutan', k: 'bt flag' },
    { c: '🇧🇻', n: 'flag bouvet island', k: 'bv flag' },
    { c: '🇧🇼', n: 'flag botswana', k: 'bw flag' },
    { c: '🇧🇾', n: 'flag belarus', k: 'by flag' },
    { c: '🇧🇿', n: 'flag belize', k: 'bz flag' },
    { c: '🇨🇦', n: 'flag canada', k: 'ca flag' },
    { c: '🇨🇨', n: 'flag cocos islands', k: 'cc keeling islands flag' },
    { c: '🇨🇩', n: 'flag dr congo', k: 'cd congo kinshasa drc democratic republic flag' },
    { c: '🇨🇫', n: 'flag central african republic', k: 'cf flag' },
    { c: '🇨🇬', n: 'flag congo', k: 'cg congo brazzaville republic flag' },
    { c: '🇨🇭', n: 'flag switzerland', k: 'ch swiss flag' },
    { c: '🇨🇮', n: 'flag ivory coast', k: 'ci cote divoire flag' },
    { c: '🇨🇰', n: 'flag cook islands', k: 'ck flag' },
    { c: '🇨🇱', n: 'flag chile', k: 'cl flag' },
    { c: '🇨🇲', n: 'flag cameroon', k: 'cm flag' },
    { c: '🇨🇳', n: 'flag china', k: 'cn chinese flag' },
    { c: '🇨🇴', n: 'flag colombia', k: 'co flag' },
    { c: '🇨🇷', n: 'flag costa rica', k: 'cr flag' },
    { c: '🇨🇺', n: 'flag cuba', k: 'cu flag' },
    { c: '🇨🇻', n: 'flag cabo verde', k: 'cv cape verde flag' },
    { c: '🇨🇼', n: 'flag curacao', k: 'cw flag' },
    { c: '🇨🇽', n: 'flag christmas island', k: 'cx flag' },
    { c: '🇨🇾', n: 'flag cyprus', k: 'cy flag' },
    { c: '🇨🇿', n: 'flag czechia', k: 'cz czech republic prague flag' },
    { c: '🇩🇪', n: 'flag germany', k: 'de deutschland flag' },
    { c: '🇩🇯', n: 'flag djibouti', k: 'dj flag' },
    { c: '🇩🇰', n: 'flag denmark', k: 'dk flag' },
    { c: '🇩🇲', n: 'flag dominica', k: 'dm flag' },
    { c: '🇩🇴', n: 'flag dominican republic', k: 'do flag' },
    { c: '🇩🇿', n: 'flag algeria', k: 'dz flag' },
    { c: '🇪🇨', n: 'flag ecuador', k: 'ec flag' },
    { c: '🇪🇪', n: 'flag estonia', k: 'ee flag' },
    { c: '🇪🇬', n: 'flag egypt', k: 'eg flag' },
    { c: '🇪🇭', n: 'flag western sahara', k: 'eh flag' },
    { c: '🇪🇷', n: 'flag eritrea', k: 'er flag' },
    { c: '🇪🇸', n: 'flag spain', k: 'es espana flag' },
    { c: '🇪🇹', n: 'flag ethiopia', k: 'et flag' },
    { c: '🇫🇮', n: 'flag finland', k: 'fi flag' },
    { c: '🇫🇯', n: 'flag fiji', k: 'fj flag' },
    { c: '🇫🇰', n: 'flag falkland islands', k: 'fk malvinas flag' },
    { c: '🇫🇲', n: 'flag micronesia', k: 'fm flag' },
    { c: '🇫🇴', n: 'flag faroe islands', k: 'fo flag' },
    { c: '🇫🇷', n: 'flag france', k: 'fr french flag' },
    { c: '🇬🇦', n: 'flag gabon', k: 'ga flag' },
    { c: '🇬🇧', n: 'flag united kingdom', k: 'gb uk britain england scotland wales british flag' },
    { c: '🇬🇩', n: 'flag grenada', k: 'gd flag' },
    { c: '🇬🇪', n: 'flag georgia', k: 'ge sakartvelo tbilisi flag' },
    { c: '🇬🇫', n: 'flag french guiana', k: 'gf flag' },
    { c: '🇬🇬', n: 'flag guernsey', k: 'gg flag' },
    { c: '🇬🇭', n: 'flag ghana', k: 'gh flag' },
    { c: '🇬🇮', n: 'flag gibraltar', k: 'gi flag' },
    { c: '🇬🇱', n: 'flag greenland', k: 'gl flag' },
    { c: '🇬🇲', n: 'flag gambia', k: 'gm flag' },
    { c: '🇬🇳', n: 'flag guinea', k: 'gn flag' },
    { c: '🇬🇵', n: 'flag guadeloupe', k: 'gp flag' },
    { c: '🇬🇶', n: 'flag equatorial guinea', k: 'gq flag' },
    { c: '🇬🇷', n: 'flag greece', k: 'gr flag' },
    { c: '🇬🇸', n: 'flag south georgia', k: 'gs south sandwich islands flag' },
    { c: '🇬🇹', n: 'flag guatemala', k: 'gt flag' },
    { c: '🇬🇺', n: 'flag guam', k: 'gu flag' },
    { c: '🇬🇼', n: 'flag guinea bissau', k: 'gw flag' },
    { c: '🇬🇾', n: 'flag guyana', k: 'gy flag' },
    { c: '🇭🇰', n: 'flag hong kong', k: 'hk flag' },
    { c: '🇭🇲', n: 'flag heard island', k: 'hm mcdonald islands flag' },
    { c: '🇭🇳', n: 'flag honduras', k: 'hn flag' },
    { c: '🇭🇷', n: 'flag croatia', k: 'hr flag' },
    { c: '🇭🇹', n: 'flag haiti', k: 'ht flag' },
    { c: '🇭🇺', n: 'flag hungary', k: 'hu flag' },
    { c: '🇮🇩', n: 'flag indonesia', k: 'id flag' },
    { c: '🇮🇪', n: 'flag ireland', k: 'ie flag' },
    { c: '🇮🇱', n: 'flag israel', k: 'il flag' },
    { c: '🇮🇲', n: 'flag isle of man', k: 'im flag' },
    { c: '🇮🇳', n: 'flag india', k: 'in flag' },
    { c: '🇮🇴', n: 'flag british indian ocean territory', k: 'io chagos flag' },
    { c: '🇮🇶', n: 'flag iraq', k: 'iq flag' },
    { c: '🇮🇷', n: 'flag iran', k: 'ir flag' },
    { c: '🇮🇸', n: 'flag iceland', k: 'is flag' },
    { c: '🇮🇹', n: 'flag italy', k: 'it flag' },
    { c: '🇯🇪', n: 'flag jersey', k: 'je flag' },
    { c: '🇯🇲', n: 'flag jamaica', k: 'jm flag' },
    { c: '🇯🇴', n: 'flag jordan', k: 'jo flag' },
    { c: '🇯🇵', n: 'flag japan', k: 'jp flag' },
    { c: '🇰🇪', n: 'flag kenya', k: 'ke flag' },
    { c: '🇰🇬', n: 'flag kyrgyzstan', k: 'kg flag' },
    { c: '🇰🇭', n: 'flag cambodia', k: 'kh flag' },
    { c: '🇰🇮', n: 'flag kiribati', k: 'ki flag' },
    { c: '🇰🇲', n: 'flag comoros', k: 'km flag' },
    { c: '🇰🇳', n: 'flag saint kitts and nevis', k: 'kn flag' },
    { c: '🇰🇵', n: 'flag north korea', k: 'kp flag' },
    { c: '🇰🇷', n: 'flag south korea', k: 'kr korea seoul flag' },
    { c: '🇰🇼', n: 'flag kuwait', k: 'kw flag' },
    { c: '🇰🇾', n: 'flag cayman islands', k: 'ky flag' },
    { c: '🇰🇿', n: 'flag kazakhstan', k: 'kz flag' },
    { c: '🇱🇦', n: 'flag laos', k: 'la flag' },
    { c: '🇱🇧', n: 'flag lebanon', k: 'lb flag' },
    { c: '🇱🇨', n: 'flag saint lucia', k: 'lc flag' },
    { c: '🇱🇮', n: 'flag liechtenstein', k: 'li flag' },
    { c: '🇱🇰', n: 'flag sri lanka', k: 'lk flag' },
    { c: '🇱🇷', n: 'flag liberia', k: 'lr flag' },
    { c: '🇱🇸', n: 'flag lesotho', k: 'ls flag' },
    { c: '🇱🇹', n: 'flag lithuania', k: 'lt flag' },
    { c: '🇱🇺', n: 'flag luxembourg', k: 'lu flag' },
    { c: '🇱🇻', n: 'flag latvia', k: 'lv flag' },
    { c: '🇱🇾', n: 'flag libya', k: 'ly flag' },
    { c: '🇲🇦', n: 'flag morocco', k: 'ma flag' },
    { c: '🇲🇨', n: 'flag monaco', k: 'mc flag' },
    { c: '🇲🇩', n: 'flag moldova', k: 'md flag' },
    { c: '🇲🇪', n: 'flag montenegro', k: 'me flag' },
    { c: '🇲🇫', n: 'flag saint martin', k: 'mf flag' },
    { c: '🇲🇬', n: 'flag madagascar', k: 'mg flag' },
    { c: '🇲🇭', n: 'flag marshall islands', k: 'mh flag' },
    { c: '🇲🇰', n: 'flag north macedonia', k: 'mk macedonia flag' },
    { c: '🇲🇱', n: 'flag mali', k: 'ml flag' },
    { c: '🇲🇲', n: 'flag myanmar', k: 'mm burma flag' },
    { c: '🇲🇳', n: 'flag mongolia', k: 'mn flag' },
    { c: '🇲🇴', n: 'flag macao', k: 'mo macau flag' },
    { c: '🇲🇵', n: 'flag northern mariana islands', k: 'mp flag' },
    { c: '🇲🇶', n: 'flag martinique', k: 'mq flag' },
    { c: '🇲🇷', n: 'flag mauritania', k: 'mr flag' },
    { c: '🇲🇸', n: 'flag montserrat', k: 'ms flag' },
    { c: '🇲🇹', n: 'flag malta', k: 'mt flag' },
    { c: '🇲🇺', n: 'flag mauritius', k: 'mu flag' },
    { c: '🇲🇻', n: 'flag maldives', k: 'mv flag' },
    { c: '🇲🇼', n: 'flag malawi', k: 'mw flag' },
    { c: '🇲🇽', n: 'flag mexico', k: 'mx flag' },
    { c: '🇲🇾', n: 'flag malaysia', k: 'my flag' },
    { c: '🇲🇿', n: 'flag mozambique', k: 'mz flag' },
    { c: '🇳🇦', n: 'flag namibia', k: 'na flag' },
    { c: '🇳🇨', n: 'flag new caledonia', k: 'nc flag' },
    { c: '🇳🇪', n: 'flag niger', k: 'ne flag' },
    { c: '🇳🇫', n: 'flag norfolk island', k: 'nf flag' },
    { c: '🇳🇬', n: 'flag nigeria', k: 'ng flag' },
    { c: '🇳🇮', n: 'flag nicaragua', k: 'ni flag' },
    { c: '🇳🇱', n: 'flag netherlands', k: 'nl holland dutch flag' },
    { c: '🇳🇴', n: 'flag norway', k: 'no flag' },
    { c: '🇳🇵', n: 'flag nepal', k: 'np flag' },
    { c: '🇳🇷', n: 'flag nauru', k: 'nr flag' },
    { c: '🇳🇺', n: 'flag niue', k: 'nu flag' },
    { c: '🇳🇿', n: 'flag new zealand', k: 'nz flag' },
    { c: '🇴🇲', n: 'flag oman', k: 'om flag' },
    { c: '🇵🇦', n: 'flag panama', k: 'pa flag' },
    { c: '🇵🇪', n: 'flag peru', k: 'pe flag' },
    { c: '🇵🇫', n: 'flag french polynesia', k: 'pf tahiti flag' },
    { c: '🇵🇬', n: 'flag papua new guinea', k: 'pg flag' },
    { c: '🇵🇭', n: 'flag philippines', k: 'ph flag' },
    { c: '🇵🇰', n: 'flag pakistan', k: 'pk flag' },
    { c: '🇵🇱', n: 'flag poland', k: 'pl flag' },
    { c: '🇵🇲', n: 'flag saint pierre and miquelon', k: 'pm flag' },
    { c: '🇵🇳', n: 'flag pitcairn islands', k: 'pn flag' },
    { c: '🇵🇷', n: 'flag puerto rico', k: 'pr flag' },
    { c: '🇵🇸', n: 'flag palestine', k: 'ps palestinian flag' },
    { c: '🇵🇹', n: 'flag portugal', k: 'pt flag' },
    { c: '🇵🇼', n: 'flag palau', k: 'pw flag' },
    { c: '🇵🇾', n: 'flag paraguay', k: 'py flag' },
    { c: '🇶🇦', n: 'flag qatar', k: 'qa flag' },
    { c: '🇷🇪', n: 'flag reunion', k: 're flag' },
    { c: '🇷🇴', n: 'flag romania', k: 'ro flag' },
    { c: '🇷🇸', n: 'flag serbia', k: 'rs flag' },
    { c: '🇷🇺', n: 'flag russia', k: 'ru russian flag' },
    { c: '🇷🇼', n: 'flag rwanda', k: 'rw flag' },
    { c: '🇸🇦', n: 'flag saudi arabia', k: 'sa flag' },
    { c: '🇸🇧', n: 'flag solomon islands', k: 'sb flag' },
    { c: '🇸🇨', n: 'flag seychelles', k: 'sc flag' },
    { c: '🇸🇩', n: 'flag sudan', k: 'sd flag' },
    { c: '🇸🇪', n: 'flag sweden', k: 'se flag' },
    { c: '🇸🇬', n: 'flag singapore', k: 'sg flag' },
    { c: '🇸🇭', n: 'flag saint helena', k: 'sh flag' },
    { c: '🇸🇮', n: 'flag slovenia', k: 'si flag' },
    { c: '🇸🇯', n: 'flag svalbard and jan mayen', k: 'sj flag' },
    { c: '🇸🇰', n: 'flag slovakia', k: 'sk flag' },
    { c: '🇸🇱', n: 'flag sierra leone', k: 'sl flag' },
    { c: '🇸🇲', n: 'flag san marino', k: 'sm flag' },
    { c: '🇸🇳', n: 'flag senegal', k: 'sn flag' },
    { c: '🇸🇴', n: 'flag somalia', k: 'so flag' },
    { c: '🇸🇷', n: 'flag suriname', k: 'sr flag' },
    { c: '🇸🇸', n: 'flag south sudan', k: 'ss flag' },
    { c: '🇸🇹', n: 'flag sao tome and principe', k: 'st flag' },
    { c: '🇸🇻', n: 'flag el salvador', k: 'sv flag' },
    { c: '🇸🇽', n: 'flag sint maarten', k: 'sx flag' },
    { c: '🇸🇾', n: 'flag syria', k: 'sy flag' },
    { c: '🇸🇿', n: 'flag eswatini', k: 'sz swaziland flag' },
    { c: '🇹🇨', n: 'flag turks and caicos islands', k: 'tc flag' },
    { c: '🇹🇩', n: 'flag chad', k: 'td flag' },
    { c: '🇹🇫', n: 'flag french southern territories', k: 'tf flag' },
    { c: '🇹🇬', n: 'flag togo', k: 'tg flag' },
    { c: '🇹🇭', n: 'flag thailand', k: 'th flag' },
    { c: '🇹🇯', n: 'flag tajikistan', k: 'tj flag' },
    { c: '🇹🇰', n: 'flag tokelau', k: 'tk flag' },
    { c: '🇹🇱', n: 'flag timor leste', k: 'tl east timor flag' },
    { c: '🇹🇲', n: 'flag turkmenistan', k: 'tm flag' },
    { c: '🇹🇳', n: 'flag tunisia', k: 'tn flag' },
    { c: '🇹🇴', n: 'flag tonga', k: 'to flag' },
    { c: '🇹🇷', n: 'flag turkiye', k: 'tr turkey flag' },
    { c: '🇹🇹', n: 'flag trinidad and tobago', k: 'tt flag' },
    { c: '🇹🇻', n: 'flag tuvalu', k: 'tv flag' },
    { c: '🇹🇼', n: 'flag taiwan', k: 'tw flag' },
    { c: '🇹🇿', n: 'flag tanzania', k: 'tz flag' },
    { c: '🇺🇦', n: 'flag ukraine', k: 'ua flag' },
    { c: '🇺🇬', n: 'flag uganda', k: 'ug flag' },
    { c: '🇺🇲', n: 'flag united states minor outlying islands', k: 'um minor outlying islands flag' },
    { c: '🇺🇸', n: 'flag united states', k: 'us usa america american flag' },
    { c: '🇺🇾', n: 'flag uruguay', k: 'uy flag' },
    { c: '🇺🇿', n: 'flag uzbekistan', k: 'uz flag' },
    { c: '🇻🇦', n: 'flag vatican city', k: 'va holy see flag' },
    { c: '🇻🇨', n: 'flag saint vincent and the grenadines', k: 'vc saint vincent grenadines flag' },
    { c: '🇻🇪', n: 'flag venezuela', k: 've flag' },
    { c: '🇻🇬', n: 'flag british virgin islands', k: 'vg flag' },
    { c: '🇻🇮', n: 'flag virgin islands us', k: 'vi us virgin islands flag' },
    { c: '🇻🇳', n: 'flag vietnam', k: 'vn flag' },
    { c: '🇻🇺', n: 'flag vanuatu', k: 'vu flag' },
    { c: '🇼🇫', n: 'flag wallis and futuna', k: 'wf flag' },
    { c: '🇼🇸', n: 'flag samoa', k: 'ws flag' },
    { c: '🇾🇪', n: 'flag yemen', k: 'ye flag' },
    { c: '🇾🇹', n: 'flag mayotte', k: 'yt flag' },
    { c: '🇿🇦', n: 'flag south africa', k: 'za flag' },
    { c: '🇿🇲', n: 'flag zambia', k: 'zm flag' },
    { c: '🇿🇼', n: 'flag zimbabwe', k: 'zw flag' },
];
